// <auto-generated />
using System;
using Horizons.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Хоризонти.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260306132043_Done")]
    partial class Done
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Bio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsGuide")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("ProfileImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "7699db7d-964f-4782-8209-d76562e0fece",
                            AccessFailedCount = 0,
                            Age = 30,
                            Bio = "Main administrator of Horizons.",
                            ConcurrencyStamp = "4b398b1f-b3ff-486d-9d74-8ca2b6302c25",
                            Email = "admin@horizons.com",
                            EmailConfirmed = true,
                            IsGuide = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@HORIZONS.COM",
                            NormalizedUserName = "ADMIN@HORIZONS.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAENxALLEAhoLlh+li22VHj/ydGmcdmU+ZMBpYm58EH+RvK2bYbVZ0wOUgtiRU0Cn4ug==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "STATIC_SECURITY_STAMP",
                            TwoFactorEnabled = false,
                            UserName = "admin@horizons.com"
                        },
                        new
                        {
                            Id = "11111111-1111-1111-1111-111111111111",
                            AccessFailedCount = 0,
                            Age = 34,
                            Bio = "Планински гид с над 10 години опит в Родопите. Специализира в пещерни маршрути и високопланински преходи.",
                            ConcurrencyStamp = "f6f07e14-fded-435e-b71f-894781b86b36",
                            Email = "ivan.petrov@horizons.com",
                            EmailConfirmed = true,
                            IsGuide = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "IVAN.PETROV@HORIZONS.COM",
                            NormalizedUserName = "IVAN.PETROV@HORIZONS.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEK6e1d+aZXrTbvk17GMbSJkNTpYaNgWQAjsc4PzlPPyVv+i19+ZegUv2CmqbFdy5HA==",
                            PhoneNumberConfirmed = false,
                            ProfileImageUrl = "/images/planinaM.png",
                            SecurityStamp = "GUIDE1_SECURITY",
                            TwoFactorEnabled = false,
                            UserName = "ivan.petrov@horizons.com"
                        },
                        new
                        {
                            Id = "22222222-2222-2222-2222-222222222222",
                            AccessFailedCount = 0,
                            Age = 29,
                            Bio = "Лицензиран екскурзовод и любител на екопътеките. Организира турове до водопади и панорамни площадки.",
                            ConcurrencyStamp = "805ea8ea-4fcf-4865-b70b-fb5b0aca3694",
                            Email = "maria.stoyanova@horizons.com",
                            EmailConfirmed = true,
                            IsGuide = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "MARIA.STOYANOVA@HORIZONS.COM",
                            NormalizedUserName = "MARIA.STOYANOVA@HORIZONS.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEMN44vu0ZlETJ4/gl2WqFRJjELzW1RRbTZ+Uy2xuzYpbftWNooj7Vk4QhFSPF0F/4A==",
                            PhoneNumberConfirmed = false,
                            ProfileImageUrl = "/images/jenaE.png",
                            SecurityStamp = "GUIDE2_SECURITY",
                            TwoFactorEnabled = false,
                            UserName = "maria.stoyanova@horizons.com"
                        },
                        new
                        {
                            Id = "33333333-3333-3333-3333-333333333333",
                            AccessFailedCount = 0,
                            Age = 41,
                            Bio = "Специалист по исторически маршрути и тракийски светилища. Разказвач на легенди и местен фолклор.",
                            ConcurrencyStamp = "4a15f6cd-66bf-484c-a49d-58a0a10ed224",
                            Email = "georgi.dimitrov@horizons.com",
                            EmailConfirmed = true,
                            IsGuide = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "GEORGI.DIMITROV@HORIZONS.COM",
                            NormalizedUserName = "GEORGI.DIMITROV@HORIZONS.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAENNJuFS4vRSQMBYemGXJr57q8Ak2RPBhkvjgKeyRKb89I6o23P4og9j7PcDnDWXpfQ==",
                            PhoneNumberConfirmed = false,
                            ProfileImageUrl = "/images/svetilishtaM.png",
                            SecurityStamp = "GUIDE3_SECURITY",
                            TwoFactorEnabled = false,
                            UserName = "georgi.dimitrov@horizons.com"
                        },
                        new
                        {
                            Id = "44444444-4444-4444-4444-444444444444",
                            AccessFailedCount = 0,
                            Age = 32,
                            Bio = "Професионален планински водач, сертифициран за зимни преходи и снежни маршрути.",
                            ConcurrencyStamp = "8ad8a40e-a677-4487-8046-b12bb811ae9e",
                            Email = "elena.ivanova@horizons.com",
                            EmailConfirmed = true,
                            IsGuide = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ELENA.IVANOVA@HORIZONS.COM",
                            NormalizedUserName = "ELENA.IVANOVA@HORIZONS.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEGBKjwB0QYbqlJaJ91R54UyF4kVY4pH6i+qVYUKylrME3E1I+zZA29OQRJWgfkunVA==",
                            PhoneNumberConfirmed = false,
                            ProfileImageUrl = "/images/vurhh.png",
                            SecurityStamp = "GUIDE4_SECURITY",
                            TwoFactorEnabled = false,
                            UserName = "elena.ivanova@horizons.com"
                        },
                        new
                        {
                            Id = "55555555-5555-5555-5555-555555555555",
                            AccessFailedCount = 0,
                            Age = 38,
                            Bio = "Еко-туризъм и приключенски маршрути. Организира групови експедиции до върхове и резервати.",
                            ConcurrencyStamp = "ca0ec30f-e7a0-4180-8e5e-f8eaa78854f6",
                            Email = "nikolay.kolev@horizons.com",
                            EmailConfirmed = true,
                            IsGuide = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "NIKOLAY.KOLEV@HORIZONS.COM",
                            NormalizedUserName = "NIKOLAY.KOLEV@HORIZONS.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEIAoHFdM2SJt0EVXX2D/zNgcSht53eLvaZ38sAPGIhb3hWlixoSHL4d6GHBGWZIpig==",
                            PhoneNumberConfirmed = false,
                            ProfileImageUrl = "/images/parkoveM.png",
                            SecurityStamp = "GUIDE5_SECURITY",
                            TwoFactorEnabled = false,
                            UserName = "nikolay.kolev@horizons.com"
                        });
                });

            modelBuilder.Entity("Horizons.Data.Models.Destination", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LocationUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PublishedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("PublisherId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Season")
                        .HasColumnType("int");

                    b.Property<int>("TerrainId")
                        .HasColumnType("int");

                    b.Property<decimal>("TicketPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("VideoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PublisherId");

                    b.HasIndex("TerrainId");

                    b.ToTable("Destinations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Ягодинската пещера е една от най-дългите и красиви пещери в България, разположена в живописното Буйновско ждрело в Родопите. Общата ѝ дължина е над 10 километра, но за посетители е достъпна специално изградена туристическа част. Пещерата впечатлява с разнообразни сталактити, сталагмити, сталактони и уникални скални форми, образувани в продължение на милиони години.",
                            ImageUrl = "https://th.bing.com/th/id/R.0f6956b90ab335551ef69581b5fb249c?rik=isKYGcW46QN7Wg&riu=http%3a%2f%2fwww.torre-bg.com%2fimages%2ftravel_offer_images%2fsm.jpg&ehk=A4tcxFAyfCoYpcrgn%2bBHb5mJLTDytaoeZw4chEgjM7U%3d&risl=&pid=ImgRaw&r=0",
                            IsDeleted = false,
                            Location = "Ягодинската пещера се намира в Западните Родопи, на около 3 км южно от село Ягодина и близо до Буйновското ждрело. Районът е част от Триградския карстов район и е лесно достъпен по асфалтов път.",
                            LocationUrl = "/images/ЯП.png",
                            Name = "Ягодинска пещера",
                            PublishedOn = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PublisherId = "7699db7d-964f-4782-8209-d76562e0fece",
                            Season = 3,
                            TerrainId = 1,
                            TicketPrice = 12m,
                            VideoUrl = "https://www.youtube.com/embed/7eBi4Bq85xE"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Дяволското гърло е една от най-мистичните пещери в България, известна със своя огромен подземен водопад.",
                            ImageUrl = "https://th.bing.com/th/id/R.069ba412d447d50a586d1836cc84c66f?rik=dN5O%2b4J3ghtCwA&pid=ImgRaw&r=0",
                            IsDeleted = false,
                            Location = "Пещерата Дяволското гърло се намира в Триградското ждрело в Западните Родопи, на около 2 км от село Триград и на 25 км от град Девин.",
                            LocationUrl = "/images/ДГ.png",
                            Name = "Пещера Дяволското гърло",
                            PublishedOn = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PublisherId = "7699db7d-964f-4782-8209-d76562e0fece",
                            Season = 3,
                            TerrainId = 1,
                            TicketPrice = 15m,
                            VideoUrl = "https://www.youtube.com/embed/_dg8xrSLYcw?start=28"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Ухловица е една от най-красивите пещери в Родопите, известна със своите калцитни образувания.",
                            ImageUrl = "https://tse4.mm.bing.net/th/id/OIP.w6SkxFzGIvY4ESdZwcs3mwHaE3?rs=1&pid=ImgDetMain&o=7&rm=3",
                            IsDeleted = false,
                            Location = "Пещера Ухловица се намира близо до село Могилица в Западните Родопи, на около 37 км южно от град Смолян.",
                            LocationUrl = "/images/У.png",
                            Name = "Ухловица",
                            PublishedOn = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PublisherId = "7699db7d-964f-4782-8209-d76562e0fece",
                            Season = 3,
                            TerrainId = 1,
                            TicketPrice = 10m,
                            VideoUrl = "https://www.youtube.com/embed/KyUtzNQmQ_I"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Триградското ждрело е величествен карстов каньон...",
                            ImageUrl = "https://tse4.mm.bing.net/th/id/OIP.XcL7FSfxMczbaMFwc4YEPgHaJ4?rs=1&pid=ImgDetMain&o=7&rm=3",
                            IsDeleted = false,
                            Location = "Триградското ждрело се намира в Западните Родопи между селата Триград и Девин и е издълбано от река Триградска.",
                            LocationUrl = "/images/ТЖ.png",
                            Name = "Триградско ждрело",
                            PublishedOn = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PublisherId = "7699db7d-964f-4782-8209-d76562e0fece",
                            Season = 2,
                            TerrainId = 2,
                            TicketPrice = 0m,
                            VideoUrl = "https://www.youtube.com/embed/wmxbIB5JuCI?start=56"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Буйновското ждрело е най-дългото ждрело в България...",
                            ImageUrl = "https://tse4.mm.bing.net/th/id/OIP.LLbqun3yJfkPrZZD7Ie6xAHaDC?rs=1&pid=ImgDetMain&o=7&rm=3",
                            IsDeleted = false,
                            Location = "Буйновското ждрело се намира в Западните Родопи между селата Тешел и Ягодина и следва течението на река Буйновска.",
                            LocationUrl = "/images/БЖ.png",
                            Name = "Буйновско ждрело",
                            PublishedOn = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PublisherId = "7699db7d-964f-4782-8209-d76562e0fece",
                            Season = 2,
                            TerrainId = 2,
                            TicketPrice = 0m,
                            VideoUrl = "https://www.youtube.com/embed/RXMaOdj88B4"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Каньонът на водопадите е природен резерват...",
                            ImageUrl = "https://th.bing.com/th/id/R.a5291d2e52f73c8001355d5eb15368ca?rik=R0DvhlMQg3M4bA&riu=http%3a%2f%2fwww.bestplacesinbulgaria.com%2fwp-content%2fuploads%2f2016%2f07%2fthe-waterfall-canyon-tourist-eco-route-04.jpg&ehk=oCv5V7rhnBFogS4%2fm7xRsyWvJs0xKlq0uAwRHdAb%2fZI%3d&risl=&pid=ImgRaw&r=0",
                            IsDeleted = false,
                            Location = "Каньонът на водопадите се намира в местността Сосковчето на около 3 км южно от град Смолян.",
                            LocationUrl = "/images/КВ.png",
                            Name = "Каньонът на водопадите",
                            PublishedOn = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PublisherId = "7699db7d-964f-4782-8209-d76562e0fece",
                            Season = 2,
                            TerrainId = 2,
                            TicketPrice = 0m,
                            VideoUrl = "https://www.youtube.com/embed/3GhaDD5iaXk"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Чудните мостове са природно образувани мраморни арки...",
                            ImageUrl = "https://th.bing.com/th/id/R.b048105f8f39b372ffdea8dbcf05c795?rik=FCc9PiWL7rUe5Q&riu=http%3a%2f%2fimgrabo.com%2fpics%2fguide%2f900x600%2f20160601155206_11652.jpeg&ehk=DaVIqKNWclj1HLtnZ9PETVjw7xvfpNsSMMmVTryhjsE%3d&risl=&pid=ImgRaw&r=0",
                            IsDeleted = false,
                            Location = "Чудните мостове се намират в Западните Родопи, на около 16 км от село Забърдо и приблизително 50 км от град Пловдив.",
                            LocationUrl = "/images/ЧМ.png",
                            Name = "Чудните мостове",
                            PublishedOn = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PublisherId = "7699db7d-964f-4782-8209-d76562e0fece",
                            Season = 2,
                            TerrainId = 3,
                            TicketPrice = 0m,
                            VideoUrl = "https://www.youtube.com/embed/sGwA9KiQL-s?start=20"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Каменната сватба е група от розово-бели скални фигури...",
                            ImageUrl = "https://th.bing.com/th/id/R.dac78f30028a402c35f83f7c13014156?rik=ai36YaI2926Wgg&pid=ImgRaw&r=0",
                            IsDeleted = false,
                            Location = "Каменната сватба се намира в Източните Родопи, на около 5 км източно от град Кърджали, близо до село Зимзелен.",
                            LocationUrl = "/images/ВС.png",
                            Name = "Каменната сватба",
                            PublishedOn = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PublisherId = "7699db7d-964f-4782-8209-d76562e0fece",
                            Season = 2,
                            TerrainId = 3,
                            TicketPrice = 0m,
                            VideoUrl = "https://www.youtube.com/embed/qWWHbqvgodI"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Орфееви скали са панорамен скален масив...",
                            ImageUrl = "https://tse1.mm.bing.net/th/id/OIP.E3gs9mp6NNpTDsT5a8ZVjgHaE8?rs=1&pid=ImgDetMain&o=7&rm=3",
                            IsDeleted = false,
                            Location = "Орфееви скали се намират в Източните Родопи над язовир Студен кладенец, близо до град Кърджали.",
                            LocationUrl = "/images/ОС.png",
                            Name = "Орфееви скали",
                            PublishedOn = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PublisherId = "7699db7d-964f-4782-8209-d76562e0fece",
                            Season = 2,
                            TerrainId = 3,
                            TicketPrice = 0m,
                            VideoUrl = "https://www.youtube.com/embed/TquHEt3VnNA?start=24"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Екопътека Невястата е къса, но изключително красива пътека...",
                            ImageUrl = "https://th.bing.com/th/id/R.0a050afe7b3736527938ed15d7e9a03d?rik=57SHvi48b7i2bw&pid=ImgRaw&r=0",
                            IsDeleted = false,
                            Location = "Екопътека Невястата се намира над град Смолян в Западните Родопи и започва близо до квартал Райково.",
                            LocationUrl = "/images/Н.png",
                            Name = "Екопътека Невястата",
                            PublishedOn = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PublisherId = "7699db7d-964f-4782-8209-d76562e0fece",
                            Season = 1,
                            TerrainId = 4,
                            TicketPrice = 2m,
                            VideoUrl = "https://www.youtube.com/embed/ZKz12LqDtEo"
                        },
                        new
                        {
                            Id = 11,
                            Description = "Екопътеката разкрива уникални панорами към долината на река Въча...",
                            ImageUrl = "https://i.pinimg.com/originals/7a/ea/e5/7aeae5868a2c405cb35e18f18af472ce.jpg",
                            IsDeleted = false,
                            Location = "Екопътеката Девин – Лъки се намира в Родопите и преминава през красиви горски райони близо до град Девин.",
                            LocationUrl = "/images/ЕДЛ.png",
                            Name = "Екопътека Девин – Лъки",
                            PublishedOn = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PublisherId = "7699db7d-964f-4782-8209-d76562e0fece",
                            Season = 1,
                            TerrainId = 4,
                            TicketPrice = 0m,
                            VideoUrl = "https://www.youtube.com/embed/OnwO_cKrtOk"
                        },
                        new
                        {
                            Id = 12,
                            Description = "Това е една от най-популярните екопътеки в България...",
                            ImageUrl = "https://th.bing.com/th/id/R.9f1c32a1258db100a6f29964c02ff682?rik=oHJQwPzmxk2tYQ&pid=ImgRaw&r=0",
                            IsDeleted = false,
                            Location = "Екопътека Каньонът на водопадите се намира в местността Сосковчето на около 3 км южно от град Смолян.",
                            LocationUrl = "/images/ЕКВ.png",
                            Name = "Екопътека Каньонът на водопадите",
                            PublishedOn = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PublisherId = "7699db7d-964f-4782-8209-d76562e0fece",
                            Season = 1,
                            TerrainId = 4,
                            TicketPrice = 2m,
                            VideoUrl = "https://www.youtube.com/embed/KfT4eUp56Vc"
                        },
                        new
                        {
                            Id = 13,
                            Description = "Сливодолското падало е един от най-високите и красиви водопади в Родопите...",
                            ImageUrl = "https://th.bing.com/th/id/R.ddeeca6d4f5ce0ec0204b62cc8e37980?rik=25fdGAogwznqjw&riu=http%3a%2f%2fblog.hotel-extreme.bg%2fwp-content%2fuploads%2f2017%2f06%2f6_Fotor1400%d0%bb%d0%be%d0%b3%d0%be-min-1068x600.jpg&ehk=WkEtKlbiCqR1bwRIKog51GgKMwxRCKgwFRsxHPecX8g%3d&risl=&pid=ImgRaw&r=0",
                            IsDeleted = false,
                            Location = "Сливодолското падало се намира в Родопите, на около 15 км южно от град Асеновград, в защитената местност Сливодолско падало.",
                            LocationUrl = "/images/ВСПП.png",
                            Name = "Сливодолското падало",
                            PublishedOn = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PublisherId = "7699db7d-964f-4782-8209-d76562e0fece",
                            Season = 1,
                            TerrainId = 5,
                            TicketPrice = 0m,
                            VideoUrl = "https://www.youtube.com/embed/C7tUIZPyLgM?start=46"
                        },
                        new
                        {
                            Id = 14,
                            Description = "Според легендите тук са танцували самодиви...",
                            ImageUrl = "https://tse2.mm.bing.net/th/id/OIP.CO4dsfPS4jbawx7C25h4eQAAAA?rs=1&pid=ImgDetMain&o=7&rm=3",
                            IsDeleted = false,
                            Location = "Самодивското пръскало се намира в Родопите близо до град Девин, сред гъсти гори и планински склонове.",
                            LocationUrl = "/images/ВСП.png",
                            Name = "Самодивско пръскало",
                            PublishedOn = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PublisherId = "7699db7d-964f-4782-8209-d76562e0fece",
                            Season = 1,
                            TerrainId = 5,
                            TicketPrice = 0m,
                            VideoUrl = "https://www.youtube.com/embed/xkymhO4rF6o?start=71"
                        },
                        new
                        {
                            Id = 15,
                            Description = "Водопад Орфей е част от Каньона на водопадите...",
                            ImageUrl = "https://th.bing.com/th/id/R.5471ea23b3474a4421aca6f30071e691?rik=9xyjKKpLceVaFQ&pid=ImgRaw&r=0",
                            IsDeleted = false,
                            Location = "Водопад Орфей се намира по маршрута на екопътеката Каньонът на водопадите в местността Сосковчето край град Смолян.",
                            LocationUrl = "/images/ВО.png",
                            Name = "Водопад Орфей",
                            PublishedOn = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PublisherId = "7699db7d-964f-4782-8209-d76562e0fece",
                            Season = 1,
                            TerrainId = 5,
                            TicketPrice = 0m,
                            VideoUrl = "https://www.youtube.com/embed/vtiVLTa6CWY"
                        },
                        new
                        {
                            Id = 16,
                            Description = "Смолянските езера са група от 20 естествени езера...",
                            ImageUrl = "https://tse3.mm.bing.net/th/id/OIP.DN8OOsa-_uZWXD2EQLyFkgHaFj?rs=1&pid=ImgDetMain&o=7&rm=3",
                            IsDeleted = false,
                            Location = "Смолянските езера се намират в северната част на град Смолян, разположени по склоновете на Родопите на височина около 1500 метра.",
                            LocationUrl = "/images/СЕ.png",
                            Name = "Смолянски езера",
                            PublishedOn = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PublisherId = "7699db7d-964f-4782-8209-d76562e0fece",
                            Season = 2,
                            TerrainId = 6,
                            TicketPrice = 0m,
                            VideoUrl = "https://www.youtube.com/embed/yeXTCyjg2lE"
                        },
                        new
                        {
                            Id = 17,
                            Description = "Язовир Доспат е един от най-красивите язовири...",
                            ImageUrl = "https://tse2.mm.bing.net/th/id/OIP.WkpaLcOORed2Oc25sw9rRQHaFj?rs=1&pid=ImgDetMain&o=7&rm=3",
                            IsDeleted = false,
                            Location = "Язовир Доспат се намира в Западните Родопи между град Доспат и село Сърница и е един от най-големите язовири в планината.",
                            LocationUrl = "/images/ЯД.png",
                            Name = "Язовир Доспат",
                            PublishedOn = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PublisherId = "7699db7d-964f-4782-8209-d76562e0fece",
                            Season = 2,
                            TerrainId = 6,
                            TicketPrice = 0m,
                            VideoUrl = "https://www.youtube.com/embed/JkWGJC_kjZk?start=24"
                        },
                        new
                        {
                            Id = 18,
                            Description = "Широка поляна е любим язовир за риболовци...",
                            ImageUrl = "https://th.bing.com/th/id/R.3d8cc2eb89f0e6b7b09f5a80e9645555?rik=KH2XtILVhMcRxA&pid=ImgRaw&r=0",
                            IsDeleted = false,
                            Location = "Язовир Широка поляна се намира в Западните Родопи, на около 30 км от град Батак, заобиколен от гъсти борови гори.",
                            LocationUrl = "/images/ЯШ.png",
                            Name = "Язовир Широка поляна",
                            PublishedOn = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PublisherId = "7699db7d-964f-4782-8209-d76562e0fece",
                            Season = 2,
                            TerrainId = 6,
                            TicketPrice = 0m,
                            VideoUrl = "https://www.youtube.com/embed/ZlgSpXgvPQ4?start=53"
                        },
                        new
                        {
                            Id = 19,
                            Description = "Кормисош е огромен биосферен резерват...",
                            ImageUrl = "https://th.bing.com/th/id/R.1bddc5bf1178275fa5ceed3a41b5ba7b?rik=E5tlQ55qqhUTZw&pid=ImgRaw&r=0",
                            IsDeleted = false,
                            Location = "Резерват Кормисош се намира в централната част на Родопите и е част от защитените територии на България, известен със своите обширни гори и богато биоразнообразие.",
                            LocationUrl = "/images/ЯП.png",
                            Name = "Резерват Кормисош",
                            PublishedOn = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PublisherId = "7699db7d-964f-4782-8209-d76562e0fece",
                            Season = 3,
                            TerrainId = 7,
                            TicketPrice = 0m,
                            VideoUrl = "https://www.youtube.com/embed/yAmSJVYXewY"
                        },
                        new
                        {
                            Id = 20,
                            Description = "Червената стена е биосферен резерват под закрилата на UNESCO...",
                            ImageUrl = "https://tse1.mm.bing.net/th/id/OIP.FgtZsnzP3v-JbSbsPskOfAHaE8?rs=1&pid=ImgDetMain&o=7&rm=3",
                            IsDeleted = false,
                            Location = "Резерват Червената стена се намира в Западните Родопи близо до град Асеновград и е един от най-известните биосферни резервати в България.",
                            LocationUrl = "/images/ЧС.png",
                            Name = "Резерват Червената стена",
                            PublishedOn = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PublisherId = "7699db7d-964f-4782-8209-d76562e0fece",
                            Season = 3,
                            TerrainId = 7,
                            TicketPrice = 0m,
                            VideoUrl = "https://www.youtube.com/embed/Tbo4FVD8e0w?start=22"
                        },
                        new
                        {
                            Id = 21,
                            Description = "Боровите гори около Пампорово създават усещане за алпийски пейзаж...",
                            ImageUrl = "https://tse1.mm.bing.net/th/id/OIP.1eT0klYEsE8Vyn0m_PckzgHaFj?rs=1&pid=ImgDetMain&o=7&rm=3",
                            IsDeleted = false,
                            Location = "Боровите гори се намират около курорта Пампорово в Западните Родопи, близо до град Смолян, и са известни със своя чист въздух и красиви планински пейзажи.",
                            LocationUrl = "/images/БГ.png",
                            Name = "Борова гора край Пампорово",
                            PublishedOn = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PublisherId = "7699db7d-964f-4782-8209-d76562e0fece",
                            Season = 3,
                            TerrainId = 7,
                            TicketPrice = 0m,
                            VideoUrl = "https://www.youtube.com/embed/B0vsbEh8jtk"
                        },
                        new
                        {
                            Id = 22,
                            Description = "Голям Перелик е най-високият връх в Родопите (2191 м)...",
                            ImageUrl = "https://www.bestplacesinbulgaria.com/wp-content/uploads/2016/03/golyam_perelik_02.jpg",
                            IsDeleted = false,
                            Location = "Връх Голям Перелик се намира в централната част на Родопите и е най-високият връх в планината с височина 2191 метра.",
                            LocationUrl = "/images/ПЕР.png",
                            Name = "Връх Голям Перелик",
                            PublishedOn = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PublisherId = "7699db7d-964f-4782-8209-d76562e0fece",
                            Season = 4,
                            TerrainId = 8,
                            TicketPrice = 0m,
                            VideoUrl = "https://www.youtube.com/embed/uARzLBZ4_UA"
                        },
                        new
                        {
                            Id = 23,
                            Description = "Снежанка е известен със своята телевизионна кула...",
                            ImageUrl = "https://th.bing.com/th/id/R.38b7087237df7dea6a5c55b2bba060b0?rik=%2bBeclaLOWgBkSg&pid=ImgRaw&r=0",
                            IsDeleted = false,
                            Location = "Връх Снежанка се намира над курорта Пампорово в Западните Родопи и е известен със своята телевизионна кула и панорамна площадка.",
                            LocationUrl = "/images/СНЕЖ.png",
                            Name = "Връх Снежанка",
                            PublishedOn = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PublisherId = "7699db7d-964f-4782-8209-d76562e0fece",
                            Season = 4,
                            TerrainId = 8,
                            TicketPrice = 0m,
                            VideoUrl = "https://www.youtube.com/embed/aFIq2S2fXEI"
                        },
                        new
                        {
                            Id = 24,
                            Description = "Голям Персенк е един от най-красивите върхове в Родопите...",
                            ImageUrl = "https://tse3.mm.bing.net/th/id/OIP.S_fTI4mlWg9XtR06LbxXHwHaEL?rs=1&pid=ImgDetMain&o=7&rm=3",
                            IsDeleted = false,
                            Location = "Връх Голям Персенк се намира в Родопския дял Чернатица и е един от най-високите върхове в този район.",
                            LocationUrl = "/images/ГП.png",
                            Name = "Голям Персенк",
                            PublishedOn = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PublisherId = "7699db7d-964f-4782-8209-d76562e0fece",
                            Season = 2,
                            TerrainId = 8,
                            TicketPrice = 0m,
                            VideoUrl = "https://www.youtube.com/embed/IJbpxlSFawg"
                        },
                        new
                        {
                            Id = 25,
                            Description = "Орлово око е панорамна площадка...",
                            ImageUrl = "https://tse4.mm.bing.net/th/id/OIP.sWaV4rkPqBco2_K_4KpJYwHaFo?rs=1&pid=ImgDetMain&o=7&rm=3",
                            IsDeleted = false,
                            Location = "Панорамната площадка Орлово око се намира над Буйновското ждрело в Западните Родопи на височина около 1560 метра, близо до село Ягодина.",
                            LocationUrl = "/images/ОО.png",
                            Name = "Орлово око",
                            PublishedOn = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PublisherId = "7699db7d-964f-4782-8209-d76562e0fece",
                            Season = 2,
                            TerrainId = 9,
                            TicketPrice = 6m,
                            VideoUrl = "https://www.youtube.com/embed/uARzLBZ4_UA"
                        },
                        new
                        {
                            Id = 26,
                            Description = "Площадката предлага чудесна гледка към град Смолян...",
                            ImageUrl = "https://planinka.bg/wp-content/uploads/2024/09/DSCF5725-683x1024.webp",
                            IsDeleted = false,
                            Location = "Панорамната площадка Невястата се намира над град Смолян в Западните Родопи и предлага гледка към града и околните планински върхове.",
                            LocationUrl = "/images/ППН.png",
                            Name = "Панорамна площадка Невястата",
                            PublishedOn = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PublisherId = "7699db7d-964f-4782-8209-d76562e0fece",
                            Season = 2,
                            TerrainId = 9,
                            TicketPrice = 4m,
                            VideoUrl = "https://www.youtube.com/embed/9FvP5rcw6kk"
                        },
                        new
                        {
                            Id = 27,
                            Description = "Панорамните ридове над село Мугла...",
                            ImageUrl = "https://cs14.pikabu.ru/post_img/big/2023/08/08/4/1691469042148636877.jpg",
                            IsDeleted = false,
                            Location = "Панорамните ридове над село Мугла се намират в Западните Родопи, област Смолян, и разкриват красиви гледки към планинските долини.",
                            LocationUrl = "/images/М.png",
                            Name = "Панорама над Мугла",
                            PublishedOn = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PublisherId = "7699db7d-964f-4782-8209-d76562e0fece",
                            Season = 2,
                            TerrainId = 9,
                            TicketPrice = 0m,
                            VideoUrl = "https://www.youtube.com/embed/94xSOxLhuXY?start=46"
                        },
                        new
                        {
                            Id = 28,
                            Description = "Белинташ е едно от най-известните тракийски светилища...",
                            ImageUrl = "https://tse3.mm.bing.net/th/id/OIP.gRBxnuvSn5A0TaMMIRfL4wHaE8?rs=1&pid=ImgDetMain&o=7&rm=3",
                            IsDeleted = false,
                            Location = "Белинташ се намира в Западните Родопи близо до село Мостово и е едно от най-големите тракийски светилища в България.",
                            LocationUrl = "/images/Б.png",
                            Name = "Белинташ",
                            PublishedOn = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PublisherId = "7699db7d-964f-4782-8209-d76562e0fece",
                            Season = 1,
                            TerrainId = 10,
                            TicketPrice = 6m,
                            VideoUrl = "https://www.youtube.com/embed/b55bpx1JN48"
                        },
                        new
                        {
                            Id = 29,
                            Description = "Караджов камък е величествена скална арка...",
                            ImageUrl = "https://th.bing.com/th/id/R.1dae6b2b41ce335644aa4a7945e01631?rik=fx7pNFgWyBe1Uw&pid=ImgRaw&r=0",
                            IsDeleted = false,
                            Location = "Караджов камък се намира в Родопите близо до село Мостово, недалеч от тракийското светилище Белинташ.",
                            LocationUrl = "/images/KK.png",
                            Name = "Караджов камък",
                            PublishedOn = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PublisherId = "7699db7d-964f-4782-8209-d76562e0fece",
                            Season = 1,
                            TerrainId = 10,
                            TicketPrice = 6m,
                            VideoUrl = "https://www.youtube.com/embed/s4iG2ux2gQc?start=28"
                        },
                        new
                        {
                            Id = 30,
                            Description = "Татул е древно тракийско светилище...",
                            ImageUrl = "https://tse3.mm.bing.net/th/id/OIP.qmgnBIPyzwGyuIeDA4L38gHaE8?rs=1&pid=ImgDetMain&o=7&rm=3",
                            IsDeleted = false,
                            Location = "Тракийското светилище Татул се намира в Източните Родопи близо до село Татул, на около 15 км от град Момчилград.",
                            LocationUrl = "/images/Т.png",
                            Name = "Татул",
                            PublishedOn = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PublisherId = "7699db7d-964f-4782-8209-d76562e0fece",
                            Season = 1,
                            TerrainId = 10,
                            TicketPrice = 6m,
                            VideoUrl = "https://www.youtube.com/embed/7cAKSl69e5U?start=564"
                        });
                });

            modelBuilder.Entity("Horizons.Data.Models.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int?>("DestinationId")
                        .HasColumnType("int");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("bit");

                    b.Property<string>("ReceiverId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SenderId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("SentOn")
                        .HasColumnType("datetime2");

                    b.Property<int?>("TourId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DestinationId");

                    b.HasIndex("ReceiverId");

                    b.HasIndex("SenderId");

                    b.HasIndex("TourId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("Horizons.Data.Models.Rating", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("DestinationId")
                        .HasColumnType("int");

                    b.Property<int>("Stars")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("DestinationId");

                    b.HasIndex("UserId");

                    b.ToTable("Ratings");
                });

            modelBuilder.Entity("Horizons.Data.Models.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("DestinationId")
                        .HasColumnType("int");

                    b.Property<int>("PeopleCount")
                        .HasColumnType("int");

                    b.Property<decimal>("TicketPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("DestinationId");

                    b.HasIndex("UserId");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("Horizons.Data.Models.Terrain", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Terrains");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Пещера"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Ждрело / Каньон"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Скални образувания"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Екопътека"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Водопад"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Езеро"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Гора / Резерват"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Връх"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Панорамна площадка"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Светилище / Историческо място"
                        });
                });

            modelBuilder.Entity("Horizons.Data.Models.TourReservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("bit");

                    b.Property<bool>("IsCancelled")
                        .HasColumnType("bit");

                    b.Property<int>("PeopleCount")
                        .HasColumnType("int");

                    b.Property<decimal>("PricePerPerson")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TourId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("TourId");

                    b.HasIndex("UserId");

                    b.ToTable("TourReservations");
                });

            modelBuilder.Entity("Horizons.Data.Models.UserDestination", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("DestinationId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "DestinationId");

                    b.HasIndex("DestinationId");

                    b.ToTable("UserDestinations");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Tour", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DestinationId")
                        .HasColumnType("int");

                    b.Property<string>("GuideId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("MaxPeople")
                        .HasColumnType("int");

                    b.Property<decimal>("PricePerPerson")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("DestinationId");

                    b.HasIndex("GuideId");

                    b.ToTable("Tours");
                });

            modelBuilder.Entity("Horizons.Data.Models.Destination", b =>
                {
                    b.HasOne("ApplicationUser", "Publisher")
                        .WithMany()
                        .HasForeignKey("PublisherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Horizons.Data.Models.Terrain", "Terrain")
                        .WithMany("Destinations")
                        .HasForeignKey("TerrainId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Publisher");

                    b.Navigation("Terrain");
                });

            modelBuilder.Entity("Horizons.Data.Models.Message", b =>
                {
                    b.HasOne("Horizons.Data.Models.Destination", "Destination")
                        .WithMany()
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ApplicationUser", "Receiver")
                        .WithMany()
                        .HasForeignKey("ReceiverId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ApplicationUser", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Tour", "Tour")
                        .WithMany()
                        .HasForeignKey("TourId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Destination");

                    b.Navigation("Receiver");

                    b.Navigation("Sender");

                    b.Navigation("Tour");
                });

            modelBuilder.Entity("Horizons.Data.Models.Rating", b =>
                {
                    b.HasOne("Horizons.Data.Models.Destination", "Destination")
                        .WithMany()
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Destination");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Horizons.Data.Models.Reservation", b =>
                {
                    b.HasOne("Horizons.Data.Models.Destination", "Destination")
                        .WithMany()
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Destination");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Horizons.Data.Models.TourReservation", b =>
                {
                    b.HasOne("Tour", "Tour")
                        .WithMany("Reservations")
                        .HasForeignKey("TourId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tour");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Horizons.Data.Models.UserDestination", b =>
                {
                    b.HasOne("Horizons.Data.Models.Destination", "Destination")
                        .WithMany()
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Destination");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Tour", b =>
                {
                    b.HasOne("Horizons.Data.Models.Destination", "Destination")
                        .WithMany()
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ApplicationUser", "Guide")
                        .WithMany()
                        .HasForeignKey("GuideId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Destination");

                    b.Navigation("Guide");
                });

            modelBuilder.Entity("Horizons.Data.Models.Terrain", b =>
                {
                    b.Navigation("Destinations");
                });

            modelBuilder.Entity("Tour", b =>
                {
                    b.Navigation("Reservations");
                });
#pragma warning restore 612, 618
        }
    }
}
