// <auto-generated />
using System;
using Horizons.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Хоризонти.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251122210351_Edity")]
    partial class Edity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Horizons.Data.Models.Destination", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PublishedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("PublisherId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("TerrainId")
                        .HasColumnType("int");

                    b.Property<decimal>("TicketPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("PublisherId");

                    b.HasIndex("TerrainId");

                    b.ToTable("Destinations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Карстова пещера в Буйновското ждрело.",
                            ImageUrl = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTxKcGnaJ44fvZ04MDrBy6cfa6enZfFGmFIBw&s",
                            IsDeleted = false,
                            Name = "Ягодинска пещера",
                            PublishedOn = new DateTime(2025, 11, 22, 23, 3, 51, 624, DateTimeKind.Local).AddTicks(4460),
                            PublisherId = "7699db7d-964f-4782-8209-d76562e0fece",
                            TerrainId = 1,
                            TicketPrice = 12m
                        },
                        new
                        {
                            Id = 2,
                            Description = "Пропастна пещера в Триградското ждрело.",
                            ImageUrl = "https://pateka.im/wp-content/uploads/2021/08/Dyavolskoto-gurlo-16.jpg",
                            IsDeleted = false,
                            Name = "Пещера Дяволското гърло",
                            PublishedOn = new DateTime(2025, 11, 22, 23, 3, 51, 624, DateTimeKind.Local).AddTicks(4460),
                            PublisherId = "7699db7d-964f-4782-8209-d76562e0fece",
                            TerrainId = 1,
                            TicketPrice = 15m
                        },
                        new
                        {
                            Id = 3,
                            Description = "Една от най-красивите благоустроени пещери.",
                            ImageUrl = "https://visitsmolyan.bg/wp-content/uploads/2021/04/Пещера-Ухловица.jpg",
                            IsDeleted = false,
                            Name = "Ухловица",
                            PublishedOn = new DateTime(2025, 11, 22, 23, 3, 51, 624, DateTimeKind.Local).AddTicks(4460),
                            PublisherId = "7699db7d-964f-4782-8209-d76562e0fece",
                            TerrainId = 1,
                            TicketPrice = 10m
                        },
                        new
                        {
                            Id = 4,
                            Description = "Карстово ждрело.",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/4/45/Trigrad_gorge.jpg",
                            IsDeleted = false,
                            Name = "Триградско ждрело",
                            PublishedOn = new DateTime(2025, 11, 22, 23, 3, 51, 624, DateTimeKind.Local).AddTicks(4460),
                            PublisherId = "7699db7d-964f-4782-8209-d76562e0fece",
                            TerrainId = 2,
                            TicketPrice = 0m
                        },
                        new
                        {
                            Id = 5,
                            Description = "Най-дългото ждрело в България.",
                            ImageUrl = "https://romantika-bg.com/images/Buinovsko_jdrelo.jpg",
                            IsDeleted = false,
                            Name = "Буйновско ждрело",
                            PublishedOn = new DateTime(2025, 11, 22, 23, 3, 51, 624, DateTimeKind.Local).AddTicks(4460),
                            PublisherId = "7699db7d-964f-4782-8209-d76562e0fece",
                            TerrainId = 2,
                            TicketPrice = 0m
                        },
                        new
                        {
                            Id = 6,
                            Description = "Резерват с водопади.",
                            ImageUrl = "https://patepisanici.com/wp-content/uploads/2019/01/05-1.jpg",
                            IsDeleted = false,
                            Name = "Каньонът на водопадите",
                            PublishedOn = new DateTime(2025, 11, 22, 23, 3, 51, 624, DateTimeKind.Local).AddTicks(4460),
                            PublisherId = "7699db7d-964f-4782-8209-d76562e0fece",
                            TerrainId = 2,
                            TicketPrice = 0m
                        },
                        new
                        {
                            Id = 7,
                            Description = "Мраморни скални арки.",
                            ImageUrl = "https://www.chudnitemostove.bgsait.com/assets/images/850x566.jpeg",
                            IsDeleted = false,
                            Name = "Чудните мостове",
                            PublishedOn = new DateTime(2025, 11, 22, 23, 3, 51, 624, DateTimeKind.Local).AddTicks(4460),
                            PublisherId = "7699db7d-964f-4782-8209-d76562e0fece",
                            TerrainId = 3,
                            TicketPrice = 0m
                        },
                        new
                        {
                            Id = 8,
                            Description = "Скални фигури край Кърджали.",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/8/80/Kamenna_svatba.jpg",
                            IsDeleted = false,
                            Name = "Каменната сватба",
                            PublishedOn = new DateTime(2025, 11, 22, 23, 3, 51, 624, DateTimeKind.Local).AddTicks(4460),
                            PublisherId = "7699db7d-964f-4782-8209-d76562e0fece",
                            TerrainId = 3,
                            TicketPrice = 0m
                        },
                        new
                        {
                            Id = 9,
                            Description = "Панорама над Смолян.",
                            ImageUrl = "https://imgrabo.com/pics/guide/20170905124603_35581.jpg",
                            IsDeleted = false,
                            Name = "Орфееви скали",
                            PublishedOn = new DateTime(2025, 11, 22, 23, 3, 51, 624, DateTimeKind.Local).AddTicks(4460),
                            PublisherId = "7699db7d-964f-4782-8209-d76562e0fece",
                            TerrainId = 3,
                            TicketPrice = 0m
                        },
                        new
                        {
                            Id = 10,
                            Description = "Панорама над Смолян.",
                            ImageUrl = "https://imgrabo.com/pics/guide/900x600/20210413115332_92103.jpeg",
                            IsDeleted = false,
                            Name = "Екопътека Невястата",
                            PublishedOn = new DateTime(2025, 11, 22, 23, 3, 51, 624, DateTimeKind.Local).AddTicks(4460),
                            PublisherId = "7699db7d-964f-4782-8209-d76562e0fece",
                            TerrainId = 4,
                            TicketPrice = 2m
                        },
                        new
                        {
                            Id = 11,
                            Description = "Маршрут през долината на Въча.",
                            ImageUrl = "https://planinka.bg/wp-content/uploads/2024/05/DSCF2704.jpg",
                            IsDeleted = false,
                            Name = "Екопътека Девин – Лъки",
                            PublishedOn = new DateTime(2025, 11, 22, 23, 3, 51, 624, DateTimeKind.Local).AddTicks(4460),
                            PublisherId = "7699db7d-964f-4782-8209-d76562e0fece",
                            TerrainId = 4,
                            TicketPrice = 0m
                        },
                        new
                        {
                            Id = 12,
                            Description = "Кръгов маршрут към водопадите.",
                            ImageUrl = "https://drumivdumi.com/wp-content/uploads/2020/11/ekopyteka.jpg",
                            IsDeleted = false,
                            Name = "Екопътека Каньонът на водопадите",
                            PublishedOn = new DateTime(2025, 11, 22, 23, 3, 51, 624, DateTimeKind.Local).AddTicks(4460),
                            PublisherId = "7699db7d-964f-4782-8209-d76562e0fece",
                            TerrainId = 4,
                            TicketPrice = 2m
                        },
                        new
                        {
                            Id = 13,
                            Description = "Висок водопад в Добростан.",
                            ImageUrl = "https://drumivdumi.com/wp-content/uploads/2015/07/slivodolsko.jpg",
                            IsDeleted = false,
                            Name = "Сливодолското падало",
                            PublishedOn = new DateTime(2025, 11, 22, 23, 3, 51, 624, DateTimeKind.Local).AddTicks(4460),
                            PublisherId = "7699db7d-964f-4782-8209-d76562e0fece",
                            TerrainId = 5,
                            TicketPrice = 0m
                        },
                        new
                        {
                            Id = 14,
                            Description = "Водопад в Червената стена.",
                            ImageUrl = "https://waterfallsbg.info/assets/Samodivskoto.jpg",
                            IsDeleted = false,
                            Name = "Самодивско пръскало",
                            PublishedOn = new DateTime(2025, 11, 22, 23, 3, 51, 624, DateTimeKind.Local).AddTicks(4460),
                            PublisherId = "7699db7d-964f-4782-8209-d76562e0fece",
                            TerrainId = 5,
                            TicketPrice = 0m
                        },
                        new
                        {
                            Id = 15,
                            Description = "Каскада в Каньона на водопадите.",
                            ImageUrl = "https://drumivdumi.com/wp-content/uploads/2016/08/orfei.jpg",
                            IsDeleted = false,
                            Name = "Водопад Орфей",
                            PublishedOn = new DateTime(2025, 11, 22, 23, 3, 51, 624, DateTimeKind.Local).AddTicks(4460),
                            PublisherId = "7699db7d-964f-4782-8209-d76562e0fece",
                            TerrainId = 5,
                            TicketPrice = 0m
                        },
                        new
                        {
                            Id = 16,
                            Description = "Група естествени езера.",
                            ImageUrl = "https://visitsmolyan.bg/wp-content/uploads/2020/11/smolyan-lakes.jpg",
                            IsDeleted = false,
                            Name = "Смолянски езера",
                            PublishedOn = new DateTime(2025, 11, 22, 23, 3, 51, 624, DateTimeKind.Local).AddTicks(4460),
                            PublisherId = "7699db7d-964f-4782-8209-d76562e0fece",
                            TerrainId = 6,
                            TicketPrice = 0m
                        },
                        new
                        {
                            Id = 17,
                            Description = "Голям язовир.",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/f/fb/Yazovir_dospat_40.jpg",
                            IsDeleted = false,
                            Name = "Язовир Доспат",
                            PublishedOn = new DateTime(2025, 11, 22, 23, 3, 51, 624, DateTimeKind.Local).AddTicks(4460),
                            PublisherId = "7699db7d-964f-4782-8209-d76562e0fece",
                            TerrainId = 6,
                            TicketPrice = 0m
                        },
                        new
                        {
                            Id = 18,
                            Description = "Планински язовир.",
                            ImageUrl = "https://static.pochivka.bg/sights.jpg",
                            IsDeleted = false,
                            Name = "Язовир Широка поляна",
                            PublishedOn = new DateTime(2025, 11, 22, 23, 3, 51, 624, DateTimeKind.Local).AddTicks(4460),
                            PublisherId = "7699db7d-964f-4782-8209-d76562e0fece",
                            TerrainId = 6,
                            TicketPrice = 0m
                        },
                        new
                        {
                            Id = 19,
                            Description = "Голям биосферен резерват.",
                            ImageUrl = "https://static.pochivka.bg/kormisosh.jpg",
                            IsDeleted = false,
                            Name = "Резерват Кормисош",
                            PublishedOn = new DateTime(2025, 11, 22, 23, 3, 51, 624, DateTimeKind.Local).AddTicks(4460),
                            PublisherId = "7699db7d-964f-4782-8209-d76562e0fece",
                            TerrainId = 7,
                            TicketPrice = 0m
                        },
                        new
                        {
                            Id = 20,
                            Description = "Защитена зона с водопади.",
                            ImageUrl = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSiGCZA",
                            IsDeleted = false,
                            Name = "Резерват Червената стена",
                            PublishedOn = new DateTime(2025, 11, 22, 23, 3, 51, 624, DateTimeKind.Local).AddTicks(4460),
                            PublisherId = "7699db7d-964f-4782-8209-d76562e0fece",
                            TerrainId = 7,
                            TicketPrice = 0m
                        },
                        new
                        {
                            Id = 21,
                            Description = "Иглолистна гора.",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/6/69/Pamporovoresort.jpg",
                            IsDeleted = false,
                            Name = "Борова гора край Пампорово",
                            PublishedOn = new DateTime(2025, 11, 22, 23, 3, 51, 624, DateTimeKind.Local).AddTicks(4460),
                            PublisherId = "7699db7d-964f-4782-8209-d76562e0fece",
                            TerrainId = 7,
                            TicketPrice = 0m
                        },
                        new
                        {
                            Id = 22,
                            Description = "2191 м – най-високият в Родопите.",
                            ImageUrl = "https://static.pochivka.bg/perelik.jpg",
                            IsDeleted = false,
                            Name = "Връх Перелик",
                            PublishedOn = new DateTime(2025, 11, 22, 23, 3, 51, 624, DateTimeKind.Local).AddTicks(4460),
                            PublisherId = "7699db7d-964f-4782-8209-d76562e0fece",
                            TerrainId = 8,
                            TicketPrice = 0m
                        },
                        new
                        {
                            Id = 23,
                            Description = "Панорама и кула.",
                            ImageUrl = "https://imgrabo.com/pics/guide/20160128144426_93270.jpg",
                            IsDeleted = false,
                            Name = "Връх Снежанка",
                            PublishedOn = new DateTime(2025, 11, 22, 23, 3, 51, 624, DateTimeKind.Local).AddTicks(4460),
                            PublisherId = "7699db7d-964f-4782-8209-d76562e0fece",
                            TerrainId = 8,
                            TicketPrice = 0m
                        },
                        new
                        {
                            Id = 24,
                            Description = "Масивен връх.",
                            ImageUrl = "https://imgrabo.com/pics/guide/20170526165250_94251.jpg",
                            IsDeleted = false,
                            Name = "Голям Персенк",
                            PublishedOn = new DateTime(2025, 11, 22, 23, 3, 51, 624, DateTimeKind.Local).AddTicks(4460),
                            PublisherId = "7699db7d-964f-4782-8209-d76562e0fece",
                            TerrainId = 8,
                            TicketPrice = 0m
                        },
                        new
                        {
                            Id = 25,
                            Description = "Панорамна площадка.",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/5/5c/Yagodina_Orlovo_oko_1.jpg",
                            IsDeleted = false,
                            Name = "Орлово око",
                            PublishedOn = new DateTime(2025, 11, 22, 23, 3, 51, 624, DateTimeKind.Local).AddTicks(4460),
                            PublisherId = "7699db7d-964f-4782-8209-d76562e0fece",
                            TerrainId = 9,
                            TicketPrice = 6m
                        },
                        new
                        {
                            Id = 26,
                            Description = "Гледка към Смолян.",
                            ImageUrl = "https://izbulgaria.com/wp-content/uploads/2021/10/panoramna.jpg",
                            IsDeleted = false,
                            Name = "Панорамна площадка Невястата",
                            PublishedOn = new DateTime(2025, 11, 22, 23, 3, 51, 624, DateTimeKind.Local).AddTicks(4460),
                            PublisherId = "7699db7d-964f-4782-8209-d76562e0fece",
                            TerrainId = 9,
                            TicketPrice = 4m
                        },
                        new
                        {
                            Id = 27,
                            Description = "Високи ридове.",
                            ImageUrl = "https://visitsmolyan.bg/wp-content/uploads/2020/10/Mugla-panorama.png",
                            IsDeleted = false,
                            Name = "Панорама над Мугла",
                            PublishedOn = new DateTime(2025, 11, 22, 23, 3, 51, 624, DateTimeKind.Local).AddTicks(4460),
                            PublisherId = "7699db7d-964f-4782-8209-d76562e0fece",
                            TerrainId = 9,
                            TicketPrice = 0m
                        },
                        new
                        {
                            Id = 28,
                            Description = "Тракийско светилище.",
                            ImageUrl = "https://www.visitplovdiv.com/sites/default/files/belintash.jpg",
                            IsDeleted = false,
                            Name = "Белинташ",
                            PublishedOn = new DateTime(2025, 11, 22, 23, 3, 51, 624, DateTimeKind.Local).AddTicks(4460),
                            PublisherId = "7699db7d-964f-4782-8209-d76562e0fece",
                            TerrainId = 10,
                            TicketPrice = 6m
                        },
                        new
                        {
                            Id = 29,
                            Description = "Скално светилище.",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/c/ca/Karadzhov_kamik.jpg",
                            IsDeleted = false,
                            Name = "Караджов камък",
                            PublishedOn = new DateTime(2025, 11, 22, 23, 3, 51, 624, DateTimeKind.Local).AddTicks(4460),
                            PublisherId = "7699db7d-964f-4782-8209-d76562e0fece",
                            TerrainId = 10,
                            TicketPrice = 6m
                        },
                        new
                        {
                            Id = 30,
                            Description = "Археологически комплекс.",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/5/59/TatulSanctuaryHill.jpg",
                            IsDeleted = false,
                            Name = "Татул",
                            PublishedOn = new DateTime(2025, 11, 22, 23, 3, 51, 624, DateTimeKind.Local).AddTicks(4460),
                            PublisherId = "7699db7d-964f-4782-8209-d76562e0fece",
                            TerrainId = 10,
                            TicketPrice = 6m
                        });
                });

            modelBuilder.Entity("Horizons.Data.Models.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("DestinationId")
                        .HasColumnType("int");

                    b.Property<int>("PeopleCount")
                        .HasColumnType("int");

                    b.Property<decimal>("TicketPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("DestinationId");

                    b.HasIndex("UserId");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("Horizons.Data.Models.Terrain", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Terrains");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Пещера"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Ждрело / Каньон"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Скални образувания"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Екопътека"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Водопад"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Езеро"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Гора / Резерват"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Връх"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Панорамна площадка"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Светилище / Историческо място"
                        });
                });

            modelBuilder.Entity("Horizons.Data.Models.UserDestination", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("DestinationId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "DestinationId");

                    b.HasIndex("DestinationId");

                    b.ToTable("UserDestinations");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "7699db7d-964f-4782-8209-d76562e0fece",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "37c40eb4-8d10-4e88-b81d-aef401efdae4",
                            Email = "admin@horizons.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@HORIZONS.COM",
                            NormalizedUserName = "ADMIN@HORIZONS.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEMWRpkGkZFGFObne2AXo7nOSkyUqj2wKJi8Q3RMJf7wXryClZ5cJ/7pzUEhC7/Q7+g==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "91a561f9-baaa-4775-93cd-ed42ce4edaef",
                            TwoFactorEnabled = false,
                            UserName = "admin@horizons.com"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Horizons.Data.Models.Destination", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "Publisher")
                        .WithMany()
                        .HasForeignKey("PublisherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Horizons.Data.Models.Terrain", "Terrain")
                        .WithMany("Destinations")
                        .HasForeignKey("TerrainId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Publisher");

                    b.Navigation("Terrain");
                });

            modelBuilder.Entity("Horizons.Data.Models.Reservation", b =>
                {
                    b.HasOne("Horizons.Data.Models.Destination", "Destination")
                        .WithMany()
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Destination");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Horizons.Data.Models.UserDestination", b =>
                {
                    b.HasOne("Horizons.Data.Models.Destination", "Destination")
                        .WithMany()
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Destination");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Horizons.Data.Models.Terrain", b =>
                {
                    b.Navigation("Destinations");
                });
#pragma warning restore 612, 618
        }
    }
}
