// <auto-generated />
using System;
using Horizons.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Хоризонти.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251124175445_phAdd")]
    partial class phAdd
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Destination", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LocationUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PublishedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("PublisherId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("TerrainId")
                        .HasColumnType("int");

                    b.Property<decimal>("TicketPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("PublisherId");

                    b.HasIndex("TerrainId");

                    b.ToTable("Destinations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Карстова пещера в Буйновското ждрело.",
                            ImageUrl = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTxKcGnaJ44fvZ04MDrBy6cfa6enZfFGmFIBw&s",
                            IsDeleted = false,
                            Location = "Ягодинската пещера е разположена в Родопите, само на 3 км от село Ягодина.",
                            LocationUrl = "/images/ЯП.png",
                            Name = "Ягодинска пещера",
                            PublishedOn = new DateTime(2025, 11, 24, 19, 54, 45, 216, DateTimeKind.Local).AddTicks(1481),
                            PublisherId = "7699db7d-964f-4782-8209-d76562e0fece",
                            TerrainId = 1,
                            TicketPrice = 12m
                        },
                        new
                        {
                            Id = 2,
                            Description = "Пропастна пещера в Триградското ждрело.",
                            ImageUrl = "https://pateka.im/wp-content/uploads/2021/08/Dyavolskoto-gurlo-16.jpg",
                            IsDeleted = false,
                            Location = "Област Смолян, Западни Родопи, на по-малко от 2км от Триград, на 25км от Девин и на 34км от Доспат",
                            LocationUrl = "/images/ДГ.png",
                            Name = "Пещера Дяволското гърло",
                            PublishedOn = new DateTime(2025, 11, 24, 19, 54, 45, 216, DateTimeKind.Local).AddTicks(1481),
                            PublisherId = "7699db7d-964f-4782-8209-d76562e0fece",
                            TerrainId = 1,
                            TicketPrice = 15m
                        },
                        new
                        {
                            Id = 3,
                            Description = "Една от най-красивите благоустроени пещери.",
                            ImageUrl = "https://visitsmolyan.bg/wp-content/uploads/2021/04/Пещера-Ухловица.jpg",
                            IsDeleted = false,
                            Location = "Ухловица е село в Южна България. То се намира в община Смолян, област Смолян",
                            LocationUrl = "/images/У.png",
                            Name = "Ухловица",
                            PublishedOn = new DateTime(2025, 11, 24, 19, 54, 45, 216, DateTimeKind.Local).AddTicks(1481),
                            PublisherId = "7699db7d-964f-4782-8209-d76562e0fece",
                            TerrainId = 1,
                            TicketPrice = 10m
                        },
                        new
                        {
                            Id = 4,
                            Description = "Карстово ждрело.",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/4/45/Trigrad_gorge.jpg",
                            IsDeleted = false,
                            Location = "Започва на около 1,5 km северно от село Триград на около 1180 m н.в., където Триградска река влиза в пещерата Дяволското гърло и 530 m след това излиза като голям карстов извор. ",
                            LocationUrl = "/images/ТЖ.png",
                            Name = "Триградско ждрело",
                            PublishedOn = new DateTime(2025, 11, 24, 19, 54, 45, 216, DateTimeKind.Local).AddTicks(1481),
                            PublisherId = "7699db7d-964f-4782-8209-d76562e0fece",
                            TerrainId = 2,
                            TicketPrice = 0m
                        },
                        new
                        {
                            Id = 5,
                            Description = "Най-дългото ждрело в България.",
                            ImageUrl = "https://romantika-bg.com/images/Buinovsko_jdrelo.jpg",
                            IsDeleted = false,
                            Location = "Буйновското ждрело се намира в Родопите, северно от село Буйново, община Борино. Проломът следва течението на Буйновска река, като е достъпен за разходка от двете му страни, а най-близката голяма община е Доспат. ",
                            LocationUrl = "/images/БЖ.png",
                            Name = "Буйновско ждрело",
                            PublishedOn = new DateTime(2025, 11, 24, 19, 54, 45, 216, DateTimeKind.Local).AddTicks(1481),
                            PublisherId = "7699db7d-964f-4782-8209-d76562e0fece",
                            TerrainId = 2,
                            TicketPrice = 0m
                        },
                        new
                        {
                            Id = 6,
                            Description = "Резерват с водопади.",
                            ImageUrl = "https://patepisanici.com/wp-content/uploads/2019/01/05-1.jpg",
                            IsDeleted = false,
                            Location = "Каньонът на водопадите се намира в Родопите, близо до град Смолян. За да стигнете до него, трябва да поемете по пътя от Смолян за село Мугла и да потърсите отбивка вдясно, след стара автобаза или бетонновъзел. ",
                            LocationUrl = "/images/КВ.png",
                            Name = "Каньонът на водопадите",
                            PublishedOn = new DateTime(2025, 11, 24, 19, 54, 45, 216, DateTimeKind.Local).AddTicks(1481),
                            PublisherId = "7699db7d-964f-4782-8209-d76562e0fece",
                            TerrainId = 2,
                            TicketPrice = 0m
                        },
                        new
                        {
                            Id = 7,
                            Description = "Мраморни скални арки.",
                            ImageUrl = "https://www.chudnitemostove.bgsait.com/assets/images/850x566.jpeg",
                            IsDeleted = false,
                            Location = "Чудните мостове са разположени на около 16 км от главния път Асеновград – Смолян. Малко преди Чепеларе, идвайки от Асеновград вдясно ще видите указателна табела сочеща към Чудните мостове. С кола това разстояние се пропътува за около 20-25 мин.",
                            LocationUrl = "/images/ЧМ.png",
                            Name = "Чудните мостове",
                            PublishedOn = new DateTime(2025, 11, 24, 19, 54, 45, 216, DateTimeKind.Local).AddTicks(1481),
                            PublisherId = "7699db7d-964f-4782-8209-d76562e0fece",
                            TerrainId = 3,
                            TicketPrice = 0m
                        },
                        new
                        {
                            Id = 8,
                            Description = "Скални фигури край Кърджали.",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/8/80/Kamenna_svatba.jpg",
                            IsDeleted = false,
                            Location = "Намира  се на 5 км източно от центъра на град Кърджали, край село Зимзелен. Разположен е в Източни родопи",
                            LocationUrl = "/images/ВС.png",
                            Name = "Каменната сватба",
                            PublishedOn = new DateTime(2025, 11, 24, 19, 54, 45, 216, DateTimeKind.Local).AddTicks(1481),
                            PublisherId = "7699db7d-964f-4782-8209-d76562e0fece",
                            TerrainId = 3,
                            TicketPrice = 0m
                        },
                        new
                        {
                            Id = 9,
                            Description = "Панорама над Смолян.",
                            ImageUrl = "https://imgrabo.com/pics/guide/20170905124603_35581.jpg",
                            IsDeleted = false,
                            Location = "Орфееви скали се намира в сърцето на Родопите, недалеч от курортен комплекс Пампорово. Разположени са под самия връх, на няколко стотин метра разстояние",
                            LocationUrl = "/images/ОС.png",
                            Name = "Орфееви скали",
                            PublishedOn = new DateTime(2025, 11, 24, 19, 54, 45, 216, DateTimeKind.Local).AddTicks(1481),
                            PublisherId = "7699db7d-964f-4782-8209-d76562e0fece",
                            TerrainId = 3,
                            TicketPrice = 0m
                        },
                        new
                        {
                            Id = 10,
                            Description = "Панорама над Смолян.",
                            ImageUrl = "https://imgrabo.com/pics/guide/900x600/20210413115332_92103.jpeg",
                            IsDeleted = false,
                            Location = "Екопътека “Невястата” се намира в сърцето на Родопи, точно по средата на пътя между Смолян и Пампорово. Разположена е на 8.7 км от Смолян и на 8.9 кмот Пампорово.",
                            LocationUrl = "/images/Н.png",
                            Name = "Екопътека Невястата",
                            PublishedOn = new DateTime(2025, 11, 24, 19, 54, 45, 216, DateTimeKind.Local).AddTicks(1481),
                            PublisherId = "7699db7d-964f-4782-8209-d76562e0fece",
                            TerrainId = 4,
                            TicketPrice = 2m
                        },
                        new
                        {
                            Id = 11,
                            Description = "Маршрут през долината на Въча.",
                            ImageUrl = "https://planinka.bg/wp-content/uploads/2024/05/DSCF2704.jpg",
                            IsDeleted = false,
                            Location = "В Родопите, на около 3км от центъра на град Девин, Смолянска област, на 45км от Смолян, на 40км от Доспат",
                            LocationUrl = "/images/ЕДЛ.png",
                            Name = "Екопътека Девин – Лъки",
                            PublishedOn = new DateTime(2025, 11, 24, 19, 54, 45, 216, DateTimeKind.Local).AddTicks(1481),
                            PublisherId = "7699db7d-964f-4782-8209-d76562e0fece",
                            TerrainId = 4,
                            TicketPrice = 0m
                        },
                        new
                        {
                            Id = 12,
                            Description = "Кръгов маршрут към водопадите.",
                            ImageUrl = "https://drumivdumi.com/wp-content/uploads/2020/11/ekopyteka.jpg",
                            IsDeleted = false,
                            Location = "Само на 2-3 км от Смолян, по пътя за село Мугла е изградена красивата екопътека Каньонът на водопадите",
                            LocationUrl = "/images/ЕКВ.png",
                            Name = "Екопътека Каньонът на водопадите",
                            PublishedOn = new DateTime(2025, 11, 24, 19, 54, 45, 216, DateTimeKind.Local).AddTicks(1481),
                            PublisherId = "7699db7d-964f-4782-8209-d76562e0fece",
                            TerrainId = 4,
                            TicketPrice = 2m
                        },
                        new
                        {
                            Id = 13,
                            Description = "Висок водопад в Добростан.",
                            ImageUrl = "https://drumivdumi.com/wp-content/uploads/2015/07/slivodolsko.jpg",
                            IsDeleted = false,
                            Location = "Водопадът се намира на около 15 километра южно от Асеновград",
                            LocationUrl = "/images/ВСПП.png",
                            Name = "Сливодолското падало",
                            PublishedOn = new DateTime(2025, 11, 24, 19, 54, 45, 216, DateTimeKind.Local).AddTicks(1481),
                            PublisherId = "7699db7d-964f-4782-8209-d76562e0fece",
                            TerrainId = 5,
                            TicketPrice = 0m
                        },
                        new
                        {
                            Id = 14,
                            Description = "Водопад в Червената стена.",
                            ImageUrl = "https://waterfallsbg.info/assets/Samodivskoto.jpg",
                            IsDeleted = false,
                            Location = "в Родопите, в близост до град Девин, на 15 мин от маршрута на екопътека Струилица-Калето-Лъката, Смолянска област, на 40км от Доспат, на 45км от Смолян",
                            LocationUrl = "/images/ВСП.png",
                            Name = "Самодивско пръскало",
                            PublishedOn = new DateTime(2025, 11, 24, 19, 54, 45, 216, DateTimeKind.Local).AddTicks(1481),
                            PublisherId = "7699db7d-964f-4782-8209-d76562e0fece",
                            TerrainId = 5,
                            TicketPrice = 0m
                        },
                        new
                        {
                            Id = 15,
                            Description = "Каскада в Каньона на водопадите.",
                            ImageUrl = "https://drumivdumi.com/wp-content/uploads/2016/08/orfei.jpg",
                            IsDeleted = false,
                            Location = "Водопад Орфей се намира в местност Сосковчето, област Смолян, на 5 км от града, като е част от екопътека Каньона на водопадите.",
                            LocationUrl = "/images/ВО.png",
                            Name = "Водопад Орфей",
                            PublishedOn = new DateTime(2025, 11, 24, 19, 54, 45, 216, DateTimeKind.Local).AddTicks(1481),
                            PublisherId = "7699db7d-964f-4782-8209-d76562e0fece",
                            TerrainId = 5,
                            TicketPrice = 0m
                        },
                        new
                        {
                            Id = 16,
                            Description = "Група естествени езера.",
                            ImageUrl = "https://visitsmolyan.bg/wp-content/uploads/2020/11/smolyan-lakes.jpg",
                            IsDeleted = false,
                            Location = "В покрайнините на град Смолян, пръснати по левия склон на долината на черна река, се намират известните Смолянски езера. ",
                            LocationUrl = "/images/СЕ.png",
                            Name = "Смолянски езера",
                            PublishedOn = new DateTime(2025, 11, 24, 19, 54, 45, 216, DateTimeKind.Local).AddTicks(1481),
                            PublisherId = "7699db7d-964f-4782-8209-d76562e0fece",
                            TerrainId = 6,
                            TicketPrice = 0m
                        },
                        new
                        {
                            Id = 17,
                            Description = "Голям язовир.",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/f/fb/Yazovir_dospat_40.jpg",
                            IsDeleted = false,
                            Location = "Разположен в посока северозапад – югоизток в землищата на градовете Доспат и Сърница, които са свързани с живописен път, минаващ по североизточния му бряг.",
                            LocationUrl = "/images/ЯД.png",
                            Name = "Язовир Доспат",
                            PublishedOn = new DateTime(2025, 11, 24, 19, 54, 45, 216, DateTimeKind.Local).AddTicks(1481),
                            PublisherId = "7699db7d-964f-4782-8209-d76562e0fece",
                            TerrainId = 6,
                            TicketPrice = 0m
                        },
                        new
                        {
                            Id = 18,
                            Description = "Планински язовир.",
                            ImageUrl = "https://static.pochivka.bg/sights.jpg",
                            IsDeleted = false,
                            Location = "Язовир Широка поляна се намира в борова гора на надморска височина 1500 м в Западните Родопи, на около 30 км от Батак.",
                            LocationUrl = "/images/ЯШ.png",
                            Name = "Язовир Широка поляна",
                            PublishedOn = new DateTime(2025, 11, 24, 19, 54, 45, 216, DateTimeKind.Local).AddTicks(1481),
                            PublisherId = "7699db7d-964f-4782-8209-d76562e0fece",
                            TerrainId = 6,
                            TicketPrice = 0m
                        },
                        new
                        {
                            Id = 19,
                            Description = "Голям биосферен резерват.",
                            ImageUrl = "https://static.pochivka.bg/kormisosh.jpg",
                            IsDeleted = false,
                            Location = "Разположен в Резерват Планинският масив на Родопите",
                            LocationUrl = "/images/ЯП.png",
                            Name = "Резерват Кормисош",
                            PublishedOn = new DateTime(2025, 11, 24, 19, 54, 45, 216, DateTimeKind.Local).AddTicks(1481),
                            PublisherId = "7699db7d-964f-4782-8209-d76562e0fece",
                            TerrainId = 7,
                            TicketPrice = 0m
                        },
                        new
                        {
                            Id = 20,
                            Description = "Защитена зона с водопади.",
                            ImageUrl = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSiGCZA",
                            IsDeleted = false,
                            Location = "В сърцето на Родопите, в долината на река Чепеларска и по планинския рид Добростан.",
                            LocationUrl = "/images/ЧС.png",
                            Name = "Резерват Червената стена",
                            PublishedOn = new DateTime(2025, 11, 24, 19, 54, 45, 216, DateTimeKind.Local).AddTicks(1481),
                            PublisherId = "7699db7d-964f-4782-8209-d76562e0fece",
                            TerrainId = 7,
                            TicketPrice = 0m
                        },
                        new
                        {
                            Id = 21,
                            Description = "Иглолистна гора.",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/6/69/Pamporovoresort.jpg",
                            IsDeleted = false,
                            Location = "Намира се близо да зимния курорт на няколко километра от град Смолян",
                            LocationUrl = "/images/БГ.png",
                            Name = "Борова гора край Пампорово",
                            PublishedOn = new DateTime(2025, 11, 24, 19, 54, 45, 216, DateTimeKind.Local).AddTicks(1481),
                            PublisherId = "7699db7d-964f-4782-8209-d76562e0fece",
                            TerrainId = 7,
                            TicketPrice = 0m
                        },
                        new
                        {
                            Id = 22,
                            Description = "2191 м – най-високият в Родопите.",
                            ImageUrl = "https://static.pochivka.bg/perelik.jpg",
                            IsDeleted = false,
                            Location = "Връх Голям Перелик е най-високата точка на Родопите и се намира в най-западната част на планината.\r\nДостъп:\r\nДо подножието на върха се стига с кола до хижа Перелик, а оттам пеша за около 40-45 минути.\r\nДостъпът до самия връх Голям Перелик е забранен заради военно поделение.\r\nНай-близкият достъпен връх, до който може да се стигне, е Малък Перелик или Широколъшки снежник.\r\nАлтернативни маршрути:\r\nОт хижа Перелик има маркирани туристически маршрути до връх Широколъшки снежник, село Мугла, Гела и други интересни места.\r\nСъщо така, от хижата могат да се посетят и други забележителности като пещера Ледницата, Каньона на водопадите и пещера Дяволското гърло.\r\nГледки: От района на Перелик се откриват красиви панорамни гледки към Смолян и цялата Родопа планина. \r\nВръх Голям Перелик - Туристически пътеводител на Смолян\r\nВАЖНА ИНФОРМАЦИЯ Същинският връх Голям Перелик попада в зоната на секретно военно поделение, разположено в района. Достъпът до нег...\r\n\r\nvisitsmolyan.bg\r\n\r\nНай-високата точка в Родопите е връх Голям Перелик ...\r\n18.08.2024 г. — Най-високата точка в Родопите е връх Голям Перелик (2191) м. Той се намира на територията на военно поделение и достъ...\r\n\r\n\r\nFacebook·Божидар Савов\r\n\r\n№85 Родопи - връх Голям Перелик - 100 обекта\r\n21.12.2012 г. — Голям Перелик е най-високият връх в Родопите. Намира се на 19 км западно от Смолян. С него (2191 м) Родопите се нареж...\r\n\r\n100obekta.com\r\n\r\nПоказване на всички\r\n",
                            LocationUrl = "/images/ПЕР.png",
                            Name = "Връх Голям Перелик",
                            PublishedOn = new DateTime(2025, 11, 24, 19, 54, 45, 216, DateTimeKind.Local).AddTicks(1481),
                            PublisherId = "7699db7d-964f-4782-8209-d76562e0fece",
                            TerrainId = 8,
                            TicketPrice = 0m
                        },
                        new
                        {
                            Id = 23,
                            Description = "Панорама и кула.",
                            ImageUrl = "https://imgrabo.com/pics/guide/20160128144426_93270.jpg",
                            IsDeleted = false,
                            Location = "Намира се в Родопи, близо до Пампорово, на около 15 км от Смолян.",
                            LocationUrl = "/images/СНЕЖ.png",
                            Name = "Връх Снежанка",
                            PublishedOn = new DateTime(2025, 11, 24, 19, 54, 45, 216, DateTimeKind.Local).AddTicks(1481),
                            PublisherId = "7699db7d-964f-4782-8209-d76562e0fece",
                            TerrainId = 8,
                            TicketPrice = 0m
                        },
                        new
                        {
                            Id = 24,
                            Description = "Масивен връх.",
                            ImageUrl = "https://imgrabo.com/pics/guide/20170526165250_94251.jpg",
                            IsDeleted = false,
                            Location = "най-високият в Родопския дял Чернатица. На юг по билото е свързан с връх Мечкарски камък.",
                            LocationUrl = "/images/ГП.png",
                            Name = "Голям Персенк",
                            PublishedOn = new DateTime(2025, 11, 24, 19, 54, 45, 216, DateTimeKind.Local).AddTicks(1481),
                            PublisherId = "7699db7d-964f-4782-8209-d76562e0fece",
                            TerrainId = 8,
                            TicketPrice = 0m
                        },
                        new
                        {
                            Id = 25,
                            Description = "Панорамна площадка",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/5/5c/Yagodina_Orlovo_oko_1.jpg",
                            IsDeleted = false,
                            Location = "Орлово око е панорамна площадка, която се намира в Западните Родопи, на връх Свети Илия.",
                            LocationUrl = "/images/ОО.png",
                            Name = "Орлово око",
                            PublishedOn = new DateTime(2025, 11, 24, 19, 54, 45, 216, DateTimeKind.Local).AddTicks(1481),
                            PublisherId = "7699db7d-964f-4782-8209-d76562e0fece",
                            TerrainId = 9,
                            TicketPrice = 6m
                        },
                        new
                        {
                            Id = 26,
                            Description = "Гледка към Смолян.",
                            ImageUrl = "https://izbulgaria.com/wp-content/uploads/2021/10/panoramna.jpg",
                            IsDeleted = false,
                            Location = "Намира се над град Смолян, в планината Родопи.",
                            LocationUrl = "/images/ППН.png",
                            Name = "Панорамна площадка Невястата",
                            PublishedOn = new DateTime(2025, 11, 24, 19, 54, 45, 216, DateTimeKind.Local).AddTicks(1481),
                            PublisherId = "7699db7d-964f-4782-8209-d76562e0fece",
                            TerrainId = 9,
                            TicketPrice = 4m
                        },
                        new
                        {
                            Id = 27,
                            Description = "Високи ридове.",
                            ImageUrl = "https://visitsmolyan.bg/wp-content/uploads/2020/10/Mugla-panorama.png",
                            IsDeleted = false,
                            Location = "В в Западните Родопи, област Смолян.",
                            LocationUrl = "/images/М.png",
                            Name = "Панорама над Мугла",
                            PublishedOn = new DateTime(2025, 11, 24, 19, 54, 45, 216, DateTimeKind.Local).AddTicks(1481),
                            PublisherId = "7699db7d-964f-4782-8209-d76562e0fece",
                            TerrainId = 9,
                            TicketPrice = 0m
                        },
                        new
                        {
                            Id = 28,
                            Description = "Тракийско светилище.",
                            ImageUrl = "https://www.visitplovdiv.com/sites/default/files/belintash.jpg",
                            IsDeleted = false,
                            Location = "Белинташ се намира в Родопите, на 32,6 км от град Асеновград, над селата Врата и Мостово.",
                            LocationUrl = "/images/Б.png",
                            Name = "Белинташ",
                            PublishedOn = new DateTime(2025, 11, 24, 19, 54, 45, 216, DateTimeKind.Local).AddTicks(1481),
                            PublisherId = "7699db7d-964f-4782-8209-d76562e0fece",
                            TerrainId = 10,
                            TicketPrice = 6m
                        },
                        new
                        {
                            Id = 29,
                            Description = "Скално светилище.",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/c/ca/Karadzhov_kamik.jpg",
                            IsDeleted = false,
                            Location = "Намира се в близост до село Мостово в Западните Родопи.",
                            LocationUrl = "/images/KK.png",
                            Name = "Караджов камък",
                            PublishedOn = new DateTime(2025, 11, 24, 19, 54, 45, 216, DateTimeKind.Local).AddTicks(1481),
                            PublisherId = "7699db7d-964f-4782-8209-d76562e0fece",
                            TerrainId = 10,
                            TicketPrice = 6m
                        },
                        new
                        {
                            Id = 30,
                            Description = "Археологически комплекс.",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/5/59/TatulSanctuaryHill.jpg",
                            IsDeleted = false,
                            Location = "Татул се намира в м. Кая Башъ, в южните покрайнини на малкото източно родопско селце Татул",
                            LocationUrl = "/images/Т.png",
                            Name = "Татул",
                            PublishedOn = new DateTime(2025, 11, 24, 19, 54, 45, 216, DateTimeKind.Local).AddTicks(1481),
                            PublisherId = "7699db7d-964f-4782-8209-d76562e0fece",
                            TerrainId = 10,
                            TicketPrice = 6m
                        });
                });

            modelBuilder.Entity("Horizons.Data.Models.Rating", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("DestinationId")
                        .HasColumnType("int");

                    b.Property<int>("Stars")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("DestinationId");

                    b.HasIndex("UserId");

                    b.ToTable("Ratings");
                });

            modelBuilder.Entity("Horizons.Data.Models.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("DestinationId")
                        .HasColumnType("int");

                    b.Property<int>("PeopleCount")
                        .HasColumnType("int");

                    b.Property<decimal>("TicketPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("DestinationId");

                    b.HasIndex("UserId");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("Horizons.Data.Models.Terrain", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Terrains");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Пещера"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Ждрело / Каньон"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Скални образувания"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Екопътека"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Водопад"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Езеро"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Гора / Резерват"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Връх"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Панорамна площадка"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Светилище / Историческо място"
                        });
                });

            modelBuilder.Entity("Horizons.Data.Models.UserDestination", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("DestinationId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "DestinationId");

                    b.HasIndex("DestinationId");

                    b.ToTable("UserDestinations");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "7699db7d-964f-4782-8209-d76562e0fece",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "407a319f-611a-4732-8e4e-0eff44fe8ffb",
                            Email = "admin@horizons.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@HORIZONS.COM",
                            NormalizedUserName = "ADMIN@HORIZONS.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEIsgsZX3Rcm/RIWDIUp2c1jH+NVWnowPfSsOf2J6+jgUGF7Zn2kSh7z4olV+Ht81xw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "5e3b317f-cf10-487d-91bc-9881b69c47c4",
                            TwoFactorEnabled = false,
                            UserName = "admin@horizons.com"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Destination", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "Publisher")
                        .WithMany()
                        .HasForeignKey("PublisherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Horizons.Data.Models.Terrain", "Terrain")
                        .WithMany("Destinations")
                        .HasForeignKey("TerrainId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Publisher");

                    b.Navigation("Terrain");
                });

            modelBuilder.Entity("Horizons.Data.Models.Rating", b =>
                {
                    b.HasOne("Destination", "Destination")
                        .WithMany()
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Destination");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Horizons.Data.Models.Reservation", b =>
                {
                    b.HasOne("Destination", "Destination")
                        .WithMany()
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Destination");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Horizons.Data.Models.UserDestination", b =>
                {
                    b.HasOne("Destination", "Destination")
                        .WithMany()
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Destination");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Horizons.Data.Models.Terrain", b =>
                {
                    b.Navigation("Destinations");
                });
#pragma warning restore 612, 618
        }
    }
}
