// <auto-generated />
using System;
using Horizons.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Хоризонти.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251121111118_Edited")]
    partial class Edited
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Horizons.Data.Models.Destination", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<DateTime>("PublishedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("PublisherId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("TerrainId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PublisherId");

                    b.HasIndex("TerrainId");

                    b.ToTable("Destinations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Карстова пещера в Буйновското ждрело, част от сложна триетажна система с над 10 км галерии, богати сталактити и пещерно жилище от неолита, благоустроена и осветена за туристически посещения.",
                            ImageUrl = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTxKcGnaJ44fvZ04MDrBy6cfa6enZfFGmFIBw&s",
                            IsDeleted = false,
                            Name = "Ягодинска пещера",
                            PublishedOn = new DateTime(2025, 11, 21, 13, 11, 17, 744, DateTimeKind.Local).AddTicks(9805),
                            PublisherId = "7699db7d-964f-4782-8209-d76562e0fece",
                            TerrainId = 1
                        },
                        new
                        {
                            Id = 2,
                            Description = "Пропастна пещера в Триградското ждрело, в която подземна река образува висок водопад, влиза през естествен вход и изчезва в сифони; свързва се с митове за Орфей и слизането му в подземния свят.",
                            ImageUrl = "https://pateka.im/wp-content/uploads/2021/08/Dyavolskoto-gurlo-16.jpg",
                            IsDeleted = false,
                            Name = "Пещера Дяволското гърло",
                            PublishedOn = new DateTime(2025, 11, 21, 13, 11, 17, 744, DateTimeKind.Local).AddTicks(9805),
                            PublisherId = "7699db7d-964f-4782-8209-d76562e0fece",
                            TerrainId = 1
                        },
                        new
                        {
                            Id = 3,
                            Description = "Една от най-красивите благоустроени пещери в Родопите, разположена над село Могилица; известна с многоетажни галерии, ледникови форми, синтрови езерца и т.нар. Ледения водопад от бели кристали.",
                            ImageUrl = "https://visitsmolyan.bg/wp-content/uploads/2021/04/%D0%9F%D0%B5%D1%89%D0%B5%D1%80%D0%B0-%D0%A3%D1%85%D0%BB%D0%BE%D0%B2%D0%B8%D1%86%D0%B0-%D0%90%D0%B2%D1%82%D0%BE%D1%80-ardaadventures-8.jpg",
                            IsDeleted = false,
                            Name = "Ухловица",
                            PublishedOn = new DateTime(2025, 11, 21, 13, 11, 17, 744, DateTimeKind.Local).AddTicks(9805),
                            PublisherId = "7699db7d-964f-4782-8209-d76562e0fece",
                            TerrainId = 1
                        },
                        new
                        {
                            Id = 4,
                            Description = "Дълбоко карстово ждрело по долината на река Триградска, с отвесни скали над 250 м, тясно шосе и множество тунели; едно от най-внушителните дефилета в България и естествен вход към Дяволското гърло.",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/4/45/Trigrad_gorge.jpg",
                            IsDeleted = false,
                            Name = "Триградско ждрело",
                            PublishedOn = new DateTime(2025, 11, 21, 13, 11, 17, 744, DateTimeKind.Local).AddTicks(9805),
                            PublisherId = "7699db7d-964f-4782-8209-d76562e0fece",
                            TerrainId = 2
                        },
                        new
                        {
                            Id = 5,
                            Description = "Най-дългото ждрело в България, образувано от река Буйновска между Ягодина и Тешел; известно е с тесен каньон, впечатляващи скални венци и множество пещери, включително входа на Ягодинската пещера.",
                            ImageUrl = "https://romantika-bg.com/images/Buinovsko_jdrelo_IMG_0286_GDstyles.jpg",
                            IsDeleted = false,
                            Name = "Буйновско ждрело",
                            PublishedOn = new DateTime(2025, 11, 21, 13, 11, 17, 744, DateTimeKind.Local).AddTicks(9805),
                            PublisherId = "7699db7d-964f-4782-8209-d76562e0fece",
                            TerrainId = 2
                        },
                        new
                        {
                            Id = 6,
                            Description = "Резерват по горното течение на река Еленска над Смолян, където екопътека следва поредица от каскадни водопади, дървени мостчета и панорамни площадки сред иглолистни гори и скалисти склонове.",
                            ImageUrl = "https://patepisanici.com/wp-content/uploads/2019/01/05-1.jpg?w=2000&h=1200&crop=1",
                            IsDeleted = false,
                            Name = "Каньонът на водопадите",
                            PublishedOn = new DateTime(2025, 11, 21, 13, 11, 17, 744, DateTimeKind.Local).AddTicks(9805),
                            PublisherId = "7699db7d-964f-4782-8209-d76562e0fece",
                            TerrainId = 2
                        },
                        new
                        {
                            Id = 7,
                            Description = "Големи мраморни арки в рида Чернатица, останки от срутила се пещера, през които минава река Еркюприя; символ на Родопите и защитена местност с туристически маршрути и алпийски маршрути наблизо.",
                            ImageUrl = "https://www.chudnitemostove.bgsait.com/assets/images/850x566.jpeg",
                            IsDeleted = false,
                            Name = "Чудните мостове",
                            PublishedOn = new DateTime(2025, 11, 21, 13, 11, 17, 744, DateTimeKind.Local).AddTicks(9805),
                            PublisherId = "7699db7d-964f-4782-8209-d76562e0fece",
                            TerrainId = 3
                        },
                        new
                        {
                            Id = 8,
                            Description = "Скални образувания до село Зимзелен край Кърджали, изградени от вулканични туфи, оформени от ерозия в фигури, наподобяващи сватбено шествие; свързани са с местна легенда за нещастна любов.",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/8/80/Kamenna_svatba_-_The_Groom_and_the_Bride.jpg",
                            IsDeleted = false,
                            Name = "Каменната сватба",
                            PublishedOn = new DateTime(2025, 11, 21, 13, 11, 17, 744, DateTimeKind.Local).AddTicks(9805),
                            PublisherId = "7699db7d-964f-4782-8209-d76562e0fece",
                            TerrainId = 3
                        },
                        new
                        {
                            Id = 9,
                            Description = "Скалисто възвишение над Смолян, свързвано с легендите за Орфей; от площадките се разкриват панорамни гледки към езерата, връх Снежанка и долината, популярно място за кратки преходи и залези.",
                            ImageUrl = "https://imgrabo.com/pics/guide/20170905124603_35581.jpg",
                            IsDeleted = false,
                            Name = "Орфееви скали",
                            PublishedOn = new DateTime(2025, 11, 21, 13, 11, 17, 744, DateTimeKind.Local).AddTicks(9805),
                            PublisherId = "7699db7d-964f-4782-8209-d76562e0fece",
                            TerrainId = 3
                        },
                        new
                        {
                            Id = 10,
                            Description = "Къса, но ефектна екопътека над Смолян, която води до скален масив, свързан с легенда за мома Невяста; предлага параклис, панорамна площадка с кръст и изгледи към града и околните върхове.",
                            ImageUrl = "https://imgrabo.com/pics/guide/900x600/20210413115332_92103.jpeg",
                            IsDeleted = false,
                            Name = "Екопътека Невястата",
                            PublishedOn = new DateTime(2025, 11, 21, 13, 11, 17, 744, DateTimeKind.Local).AddTicks(9805),
                            PublisherId = "7699db7d-964f-4782-8209-d76562e0fece",
                            TerrainId = 4
                        },
                        new
                        {
                            Id = 11,
                            Description = "Маркиран маршрут в долината на река Въча, който преминава по стари пътища, мостчета и открити ридове между Девин и Лъки; съчетава горски участъци, панорамни гледки и традиционни родопски селища.",
                            ImageUrl = "https://planinka.bg/wp-content/uploads/2024/05/DSCF2704-1024x683.webp",
                            IsDeleted = false,
                            Name = "Екопътека Девин – Лъки",
                            PublishedOn = new DateTime(2025, 11, 21, 13, 11, 17, 744, DateTimeKind.Local).AddTicks(9805),
                            PublisherId = "7699db7d-964f-4782-8209-d76562e0fece",
                            TerrainId = 4
                        },
                        new
                        {
                            Id = 12,
                            Description = "Кръгов маршрут в едноименния резерват над Смолян, който изкачва дерето на Еленска река по дървени стълби и мостове покрай серия от водопади, естествени скални прагове и стари смърчови гори.",
                            ImageUrl = "https://drumivdumi.com/wp-content/uploads/2020/11/0ekopyteka_kanyona_na_vodopadite_0839.jpg",
                            IsDeleted = false,
                            Name = "Екопътека Каньонът на водопадите",
                            PublishedOn = new DateTime(2025, 11, 21, 13, 11, 17, 744, DateTimeKind.Local).AddTicks(9805),
                            PublisherId = "7699db7d-964f-4782-8209-d76562e0fece",
                            TerrainId = 4
                        },
                        new
                        {
                            Id = 13,
                            Description = "Водопад по река Сливов дол в рида Добростан, част от резерват Червената стена; с обща височина над 45 м и стръмен достъп през букови гори, смятан за един от най-високите в Родопите.",
                            ImageUrl = "https://drumivdumi.com/wp-content/uploads/2015/07/1v_nachaloto_kym_vodopad_slivodolsko_padalo_7826.jpg",
                            IsDeleted = false,
                            Name = "Сливодолското падало",
                            PublishedOn = new DateTime(2025, 11, 21, 13, 11, 17, 744, DateTimeKind.Local).AddTicks(9805),
                            PublisherId = "7699db7d-964f-4782-8209-d76562e0fece",
                            TerrainId = 5
                        },
                        new
                        {
                            Id = 14,
                            Description = "Живописен водопад в сърцето на резерват Червената стена, достигащ около 50 м височина; заобиколен от стръмни скали и гори, до него се стига по планинска пътека от село Бачково и хижа Марциганица.",
                            ImageUrl = "https://waterfallsbg.info/assets/Samodivskoto/f2085632.jpg",
                            IsDeleted = false,
                            Name = "Самодивско пръскало",
                            PublishedOn = new DateTime(2025, 11, 21, 13, 11, 17, 744, DateTimeKind.Local).AddTicks(9805),
                            PublisherId = "7699db7d-964f-4782-8209-d76562e0fece",
                            TerrainId = 5
                        },
                        new
                        {
                            Id = 15,
                            Description = "Каскаден водопад по един от притоците в Каньона на водопадите, носещ името на Орфей заради живописното си стечение по скалите; посещава се по екопътеката над Смолян в посока Перелик.",
                            ImageUrl = "https://drumivdumi.com/wp-content/uploads/2016/08/4canyon_orfej_0608.jpg",
                            IsDeleted = false,
                            Name = "Водопад Орфей",
                            PublishedOn = new DateTime(2025, 11, 21, 13, 11, 17, 744, DateTimeKind.Local).AddTicks(9805),
                            PublisherId = "7699db7d-964f-4782-8209-d76562e0fece",
                            TerrainId = 5
                        },
                        new
                        {
                            Id = 16,
                            Description = "Група от естествени ледникови и свлачищни езера, разположени по долината между Снежанка и Смолян; част от тях са запазени, други са превърнати в рибарници и туристически зони край курорта.",
                            ImageUrl = "https://visitsmolyan.bg/wp-content/uploads/2020/11/%D0%A1%D0%BC%D0%BE%D0%BB%D1%8F%D0%BD%D1%81%D0%BA%D0%B8-%D0%B5%D0%B7%D0%B5%D1%80%D0%B0-1-scaled.jpg",
                            IsDeleted = false,
                            Name = "Смолянски езера",
                            PublishedOn = new DateTime(2025, 11, 21, 13, 11, 17, 744, DateTimeKind.Local).AddTicks(9805),
                            PublisherId = "7699db7d-964f-4782-8209-d76562e0fece",
                            TerrainId = 6
                        },
                        new
                        {
                            Id = 17,
                            Description = "Голям язовир на река Доспат, разположен на надморска височина около 1200 м; известен със силно разчленено крайбрежие, борови гори, възможности за риболов, водни спортове и лагеруване.",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/f/fb/Yazovir_dospat_40.jpg",
                            IsDeleted = false,
                            Name = "Язовир Доспат",
                            PublishedOn = new DateTime(2025, 11, 21, 13, 11, 17, 744, DateTimeKind.Local).AddTicks(9805),
                            PublisherId = "7699db7d-964f-4782-8209-d76562e0fece",
                            TerrainId = 6
                        },
                        new
                        {
                            Id = 18,
                            Description = "Планински язовир между връх Голям Перелик и Баташкия дял, заобиколен от гъсти иглолистни гори и множество полуострови; популярен за къмпинг, гребане и фотография на спокойни водни пейзажи.",
                            ImageUrl = "https://static.pochivka.bg/sights.bgstay.com/images/01/1071/5465119e2e2f7.jpg",
                            IsDeleted = false,
                            Name = "Язовир Широка поляна",
                            PublishedOn = new DateTime(2025, 11, 21, 13, 11, 17, 744, DateTimeKind.Local).AddTicks(9805),
                            PublisherId = "7699db7d-964f-4782-8209-d76562e0fece",
                            TerrainId = 6
                        },
                        new
                        {
                            Id = 19,
                            Description = "Голям ловно-стопански район и биосферен резерват в Централните Родопи, съхраняващ естествени иглолистни гори и богато животинско разнообразие, включително елени, диви свине и кафява мечка.",
                            ImageUrl = "https://static.pochivka.bg/sights.bgstay.com/images/02/2748/5a37883ece1b8.jpg",
                            IsDeleted = false,
                            Name = "Резерват Кормисош",
                            PublishedOn = new DateTime(2025, 11, 21, 13, 11, 17, 744, DateTimeKind.Local).AddTicks(9805),
                            PublisherId = "7699db7d-964f-4782-8209-d76562e0fece",
                            TerrainId = 7
                        },
                        new
                        {
                            Id = 20,
                            Description = "Стръмен варовиков масив над Бачково и Асеновград, обявен за биосферен резерват заради редките си растителни видове, скални местообитания и водопади като Самодивско пръскало и Сливодолското падало.",
                            ImageUrl = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSiGCZAqUm6xoaBt5IrLzUYiQTSTCuI9KbzQw&s",
                            IsDeleted = false,
                            Name = "Резерват Червената стена",
                            PublishedOn = new DateTime(2025, 11, 21, 13, 11, 17, 744, DateTimeKind.Local).AddTicks(9805),
                            PublisherId = "7699db7d-964f-4782-8209-d76562e0fece",
                            TerrainId = 7
                        },
                        new
                        {
                            Id = 21,
                            Description = "Големи масиви от смърчови и борови гори около курорта Пампорово, поддържащи мек планински климат и множество туристически пътеки и ски писти по склоновете на връх Снежанка.",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/6/69/Pamporovoresort.jpg",
                            IsDeleted = false,
                            Name = "Борова гора край Пампорово",
                            PublishedOn = new DateTime(2025, 11, 21, 13, 11, 17, 744, DateTimeKind.Local).AddTicks(9805),
                            PublisherId = "7699db7d-964f-4782-8209-d76562e0fece",
                            TerrainId = 7
                        },
                        new
                        {
                            Id = 22,
                            Description = "Най-високият връх в Родопите с височина 2191 м, разположен в масива Перелик; на платото му има военни съоръжения, а склоновете са обрасли с иглолистни гори и пасища с панорами към голяма част от планината.",
                            ImageUrl = "https://static.pochivka.bg/sights.bgstay.com/images/00/136/541ad01c4ffec.jpg",
                            IsDeleted = false,
                            Name = "Връх Перелик",
                            PublishedOn = new DateTime(2025, 11, 21, 13, 11, 17, 744, DateTimeKind.Local).AddTicks(9805),
                            PublisherId = "7699db7d-964f-4782-8209-d76562e0fece",
                            TerrainId = 8
                        },
                        new
                        {
                            Id = 23,
                            Description = "Знаков връх над Пампорово, висок 1926 м, на който е издигната телевизионна кула с панорамна тераса; център на ски зоната с множество писти и лифтове, достъпен целогодишно по асфалтов път.",
                            ImageUrl = "https://imgrabo.com/pics/guide/900x600/20160128144426_93270.jpg",
                            IsDeleted = false,
                            Name = "Връх Снежанка",
                            PublishedOn = new DateTime(2025, 11, 21, 13, 11, 17, 744, DateTimeKind.Local).AddTicks(9805),
                            PublisherId = "7699db7d-964f-4782-8209-d76562e0fece",
                            TerrainId = 8
                        },
                        new
                        {
                            Id = 24,
                            Description = "Масивен връх в рида Чернатица, издигащ се до 2091 м над морето; известен с панорама към Чудните мостове, Баташкия дял и Рила, както и с туристическите маршрути от хижа Персенк и село Орехово.",
                            ImageUrl = "https://imgrabo.com/pics/guide/900x600/20170526165250_94251.jpg",
                            IsDeleted = false,
                            Name = "Голям Персенк",
                            PublishedOn = new DateTime(2025, 11, 21, 13, 11, 17, 744, DateTimeKind.Local).AddTicks(9805),
                            PublisherId = "7699db7d-964f-4782-8209-d76562e0fece",
                            TerrainId = 8
                        },
                        new
                        {
                            Id = 25,
                            Description = "Метална панорамна площадка над ръба на скала при връх Свети Илия над Ягодина, достигаща над 1500 м височина; предлага драматични гледки към Буйновското ждрело и билата на Родопите.",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/5/5c/Yagodina_Orlovo_oko_1.jpg",
                            IsDeleted = false,
                            Name = "Орлово око",
                            PublishedOn = new DateTime(2025, 11, 21, 13, 11, 17, 744, DateTimeKind.Local).AddTicks(9805),
                            PublisherId = "7699db7d-964f-4782-8209-d76562e0fece",
                            TerrainId = 9
                        },
                        new
                        {
                            Id = 26,
                            Description = "Съвременна площадка с метален кръст върху скалата Невястата, до която се стига по екопътека; от нея се открива гледка към Смолян, езерата и връх Снежанка, а наоколо има и въжен парк за атракции.",
                            ImageUrl = "https://izbulgaria.com/wp-content/uploads/2021/10/panoramna-ploshtadka-na-ekopateka-neviastata-1024x768.jpg",
                            IsDeleted = false,
                            Name = "Панорамна площадка Невястата",
                            PublishedOn = new DateTime(2025, 11, 21, 13, 11, 17, 744, DateTimeKind.Local).AddTicks(9805),
                            PublisherId = "7699db7d-964f-4782-8209-d76562e0fece",
                            TerrainId = 9
                        },
                        new
                        {
                            Id = 27,
                            Description = "Високите поляни и ридове над отдалеченото родопско село Мугла предлагат обширни 360° гледки към планинските масиви Перелик и Карлък, традиционни ливади, кошари и типичен селски ландшафт.",
                            ImageUrl = "https://visitsmolyan.bg/wp-content/uploads/2020/10/%D0%9C%D1%83%D0%B3%D0%BB%D0%B0-%D0%BF%D0%BE%D1%82%D1%8A%D0%BD%D0%B0%D0%BB%D0%B0-%D0%B2-%D0%BB%D0%B5%D0%BA%D0%B0-%D0%BC%D1%8A%D0%B3%D0%BB%D0%B0.png",
                            IsDeleted = false,
                            Name = "Панорама над село Мугла",
                            PublishedOn = new DateTime(2025, 11, 21, 13, 11, 17, 744, DateTimeKind.Local).AddTicks(9805),
                            PublisherId = "7699db7d-964f-4782-8209-d76562e0fece",
                            TerrainId = 9
                        },
                        new
                        {
                            Id = 28,
                            Description = "Тракийско скално плато върху риолитов масив над село Мостово, използвано като светилище и вероятен астрономически център; върху повърхността му личат издялани улеи, ямки и останки от култови съоръжения.",
                            ImageUrl = "https://www.visitplovdiv.com/sites/default/files/belintash.jpg",
                            IsDeleted = false,
                            Name = "Белинташ",
                            PublishedOn = new DateTime(2025, 11, 21, 13, 11, 17, 744, DateTimeKind.Local).AddTicks(9805),
                            PublisherId = "7699db7d-964f-4782-8209-d76562e0fece",
                            TerrainId = 10
                        },
                        new
                        {
                            Id = 29,
                            Description = "Висока скална кула в близост до Белинташ, в чието било е поставен голям каменен блок; мястото се смята за древно светилище, а до него се стига по стръмни стълби и пътеки с гледки към долината.",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/c/ca/Karadzhov_kamik.jpg",
                            IsDeleted = false,
                            Name = "Караджов камък",
                            PublishedOn = new DateTime(2025, 11, 21, 13, 11, 17, 744, DateTimeKind.Local).AddTicks(9805),
                            PublisherId = "7699db7d-964f-4782-8209-d76562e0fece",
                            TerrainId = 10
                        },
                        new
                        {
                            Id = 30,
                            Description = "Археологически комплекс край едноименното село, включващ скално светилище и мавзолей, свързван с култа към тракийски владетел или Орфей; датира от късната бронзова и ранножелязна епоха.",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/5/59/TatulSanctuaryHill.jpg",
                            IsDeleted = false,
                            Name = "Татул",
                            PublishedOn = new DateTime(2025, 11, 21, 13, 11, 17, 744, DateTimeKind.Local).AddTicks(9805),
                            PublisherId = "7699db7d-964f-4782-8209-d76562e0fece",
                            TerrainId = 10
                        });
                });

            modelBuilder.Entity("Horizons.Data.Models.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("DestinationId")
                        .HasColumnType("int");

                    b.Property<int>("PeopleCount")
                        .HasColumnType("int");

                    b.Property<decimal>("TicketPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("DestinationId");

                    b.HasIndex("UserId");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("Horizons.Data.Models.Terrain", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Terrains");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Пещера"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Ждрело / Каньон"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Скални образувания"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Екопътека"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Водопад"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Езеро"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Гора / Резерват"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Връх"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Панорамна площадка"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Светилище / Историческо място"
                        });
                });

            modelBuilder.Entity("Horizons.Data.Models.UserDestination", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("DestinationId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "DestinationId");

                    b.HasIndex("DestinationId");

                    b.ToTable("UserDestinations");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "7699db7d-964f-4782-8209-d76562e0fece",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "06ea4bc7-dabe-4b5c-9f72-30d0010c40be",
                            Email = "admin@horizons.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@HORIZONS.COM",
                            NormalizedUserName = "ADMIN@HORIZONS.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEDBjfu81LqE2FFtQlqiPCO3VuuTjaMlXmfc9ULokgHlZY8/OuGco7OwolMrHySlCRA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "54d170ed-3edb-4616-9c92-fe0897a820d2",
                            TwoFactorEnabled = false,
                            UserName = "admin@horizons.com"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Horizons.Data.Models.Destination", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "Publisher")
                        .WithMany()
                        .HasForeignKey("PublisherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Horizons.Data.Models.Terrain", "Terrain")
                        .WithMany("Destinations")
                        .HasForeignKey("TerrainId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Publisher");

                    b.Navigation("Terrain");
                });

            modelBuilder.Entity("Horizons.Data.Models.Reservation", b =>
                {
                    b.HasOne("Horizons.Data.Models.Destination", "Destination")
                        .WithMany()
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Destination");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Horizons.Data.Models.UserDestination", b =>
                {
                    b.HasOne("Horizons.Data.Models.Destination", "Destination")
                        .WithMany("UsersDestinations")
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Destination");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Horizons.Data.Models.Destination", b =>
                {
                    b.Navigation("UsersDestinations");
                });

            modelBuilder.Entity("Horizons.Data.Models.Terrain", b =>
                {
                    b.Navigation("Destinations");
                });
#pragma warning restore 612, 618
        }
    }
}
